// Writes the SDK's re-exports of the component kit (decision D1 of the panel extension
// architecture): an addon reaches the kit only through @cboxdk/cms-panel, whose /ui subpath
// exports the kit's @stable API and whose /experimental subpath its @experimental API, so the
// subpath an addon imports from says what it may rely on.
//
// It reads every export of the kit's entry, js/ui-kit/src/index.ts, with its stability tag and
// whether it is a value or a type only, and writes js/panel-sdk/src/kit/stable.ts and
// js/panel-sdk/src/kit/experimental.ts, sorted, formatted with Prettier, only when the bytes
// differ. Gate 6, `composer check:generated`, runs it and fails when the committed files differ, so
// a component the kit adds or promotes reaches the right subpath in the same change. It exits 65
// when an export of the kit carries no stability tag or two.
//
// `node js/panel-sdk/scripts/generate-entries.js [--root=<dir>]`

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import * as prettier from 'prettier';
import ts from 'typescript';

/** The kit's entry, relative to the root. */
export const KIT_ENTRY = 'js/ui-kit/src/index.ts';

/** The files this writes, relative to the root, by the stability tag of their exports. */
export const ENTRIES = {
  '@stable': 'js/panel-sdk/src/kit/stable.ts',
  '@experimental': 'js/panel-sdk/src/kit/experimental.ts',
};

/** The stability tags; an export carries exactly one. */
const TAGS = ['@stable', '@experimental'];

/**
 * @typedef {object} KitExport
 * @property {string} name
 * @property {'@stable' | '@experimental'} tag
 * @property {boolean} value whether it is a value, not only a type
 */

/**
 * Every export of the kit's entry, sorted by name, and the exports without exactly one stability
 * tag, as `<name>: ...`.
 *
 * @param {string} root
 * @returns {{ exports: KitExport[], problems: string[] }}
 */
export function kitExports(root) {
  const entry = join(root, KIT_ENTRY);
  const program = ts.createProgram([entry, join(root, 'js/ui-kit/src/css.d.ts')], {
    target: ts.ScriptTarget.ES2023,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    resolveJsonModule: true,
    strict: true,
    noEmit: true,
    types: [],
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  const module = source === undefined ? undefined : checker.getSymbolAtLocation(source);

  /** @type {KitExport[]} */
  const exports = [];
  /** @type {string[]} */
  const problems = [];

  for (const exported of module === undefined ? [] : checker.getExportsOfModule(module)) {
    const symbol =
      (exported.flags & ts.SymbolFlags.Alias) !== 0 ? checker.getAliasedSymbol(exported) : exported;
    const tags = new Set(
      (symbol.declarations ?? []).flatMap((declaration) =>
        ts
          .getJSDocTags(declaration)
          .map((tag) => `@${tag.tagName.text}`)
          .filter((tag) => TAGS.includes(tag)),
      ),
    );
    const [tag] = [...tags];

    if (tags.size !== 1 || (tag !== '@stable' && tag !== '@experimental')) {
      problems.push(
        `${exported.name}: carries ${tags.size === 0 ? 'no stability tag' : [...tags].join(' and ')}; give it exactly one of ${TAGS.join(' and ')}`,
      );
      continue;
    }

    exports.push({ name: exported.name, tag, value: (symbol.flags & ts.SymbolFlags.Value) !== 0 });
  }

  exports.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  return { exports, problems: problems.sort() };
}

/**
 * The module that re-exports the kit's exports of one stability tag.
 *
 * @param {KitExport[]} exports
 * @param {'@stable' | '@experimental'} tag
 * @returns {string}
 */
export function entryModule(exports, tag) {
  const chosen = exports.filter((exported) => exported.tag === tag);
  const values = chosen.filter((exported) => exported.value).map((exported) => exported.name);
  const types = chosen.filter((exported) => !exported.value).map((exported) => exported.name);
  const subpath = tag === '@stable' ? '/ui' : '/experimental';

  return [
    `// What @cboxdk/cms-panel${subpath} re-exports of the component kit: its ${tag} exports`,
    '// (decision D1 of the panel extension architecture).',
    '//',
    '// Generated by npm run generate:sdk from the stability tags of js/ui-kit/src/index.ts. Do not edit',
    "// this file: change the kit's tags and run npm run generate:sdk.",
    '',
    ...(values.length > 0 ? [`export { ${values.join(', ')} } from '@cboxdk/cms-ui-kit';`] : []),
    ...(types.length > 0 ? [`export type { ${types.join(', ')} } from '@cboxdk/cms-ui-kit';`] : []),
    ...(chosen.length === 0 ? ['export {};'] : []),
    '',
  ].join('\n');
}

/**
 * Writes both entries below the root, each only when its bytes differ, and gives the paths it
 * wrote, or the problems that kept it from writing.
 *
 * @param {string} root
 * @returns {Promise<{ written: string[], problems: string[] }>}
 */
export async function generateEntries(root) {
  const { exports, problems } = kitExports(root);

  if (problems.length > 0) {
    return { written: [], problems };
  }

  /** @type {string[]} */
  const written = [];
  const options = (await prettier.resolveConfig(join(root, ENTRIES['@stable']))) ?? {};

  for (const [tag, path] of /** @type {['@stable' | '@experimental', string][]} */ (
    Object.entries(ENTRIES)
  )) {
    const target = join(root, path);
    const contents = await prettier.format(entryModule(exports, tag), {
      ...options,
      filepath: target,
    });

    if (!existsSync(target) || readFileSync(target, 'utf8') !== contents) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, contents);
      written.push(path);
    }
  }

  return { written, problems: [] };
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const option = process.argv.slice(2).find((argument) => argument.startsWith('--root='));
  const root = resolve(
    option === undefined ? join(import.meta.dirname, '../../..') : option.slice('--root='.length),
  );
  const result = await generateEntries(root);

  if (result.problems.length > 0) {
    process.stderr.write(result.problems.map((problem) => `${KIT_ENTRY}: ${problem}\n`).join(''));
    process.exit(65);
  }

  process.stdout.write(
    result.written.length === 0
      ? 'generate:sdk: the kit entries are current.\n'
      : result.written.map((path) => `generate:sdk: wrote ${path}\n`).join(''),
  );
}
