<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Tests\Generation;

use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedSchema;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Cbox\Cms\Generators\Generation\Domain\GeneratorRunner;
use Cbox\Cms\Generators\Generation\Domain\Generators\GeneratedLines;
use Cbox\Cms\Generators\Generation\Domain\Generators\PhpTypeHandleEnum;
use Cbox\Cms\Generators\Generation\Domain\Generators\TypeScriptTypeHandles;
use Cbox\Cms\Generators\Generation\Domain\SchemaResolver;
use Cbox\Cms\Generators\Schema\Domain\CoreFieldType;
use Cbox\Cms\Generators\Schema\Domain\Dto\Blueprints;
use Cbox\Cms\Generators\Tests\SchemaFixtures;
use PHPUnit\Framework\Assert;

/*
 * The two M0 generators: the PHP enum and the TypeScript union of the type handles, with the
 * fields of each type and the extension fields under ext by namespace. Their output is a pure
 * function of the resolved schema: byte-identical for the same input, sorted whatever order the
 * blueprint files use, and without timestamps.
 */

/**
 * @return array<string, string> path to contents
 */
function generatedBy(Generator ...$generators): array
{
    $schema = SchemaFixtures::schema([
        'page' => ['title' => 'text', 'slug' => 'text'],
        'blog_post' => ['title' => 'text', 'body' => 'rich_text', 'author' => 'acme:person'],
    ]);

    return contentsOf(new GeneratorRunner(array_values($generators))->run($schema, SchemaFixtures::target())->files);
}

/**
 * @param  list<GeneratedFile>  $files
 * @return array<string, string>
 */
function contentsOf(array $files): array
{
    $contents = [];

    foreach ($files as $file) {
        $contents[$file->path] = $file->contents;
    }

    return $contents;
}

it('writes a string-backed PHP enum with one case per type and the fields of each type', function (): void {
    expect(generatedBy(new PhpTypeHandleEnum))->toBe(['app/Cms/Generated/TypeHandle.php' => <<<'PHP'
        <?php

        declare(strict_types=1);

        namespace App\Cms\Generated;

        /**
         * The type handles of the schema roots, with the fields of each type.
         *
         * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
         * this file: change the blueprints and run cms:generate.
         *
         * Schema roots, by owner:
         *   app: schema
         */
        enum TypeHandle: string
        {
            case BlogPost = 'blog_post';
            case Page = 'page';

            /**
             * The type's own fields: field handle to field type, sorted by handle.
             *
             * @return array<string, string>
             */
            public function fields(): array
            {
                return match ($this) {
                    self::BlogPost => [
                        'author' => 'acme:person',
                        'body' => 'rich_text',
                        'title' => 'text',
                    ],
                    self::Page => [
                        'slug' => 'text',
                        'title' => 'text',
                    ],
                };
            }

            /**
             * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
             * namespace to field handle to field type, sorted by namespace and handle.
             *
             * @return array<string, array<string, string>>
             */
            public function extensionFields(): array
            {
                return match ($this) {
                    self::BlogPost => [],
                    self::Page => [],
                };
            }
        }

        PHP]);
});

it('writes a TypeScript union of the type handles and an interface of their fields', function (): void {
    expect(generatedBy(new TypeScriptTypeHandles))->toBe(['resources/js/cms/generated/index.ts' => <<<'TS'
        // The type handles of the schema roots, with the fields of each type.
        //
        // Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
        // this file: change the blueprints and run cms:generate.
        //
        // Schema roots, by owner:
        //   app: schema

        /** The handle of each type in the schema. */
        export type TypeHandle = 'blog_post' | 'page';

        /** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */
        export interface TypeFields {
          blog_post: {
            author: 'acme:person';
            body: 'rich_text';
            title: 'text';
          };
          page: {
            slug: 'text';
            title: 'text';
          };
        }

        TS]);
});

it('gives byte-identical output for the same input', function (): void {
    $first = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);
    $second = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);

    expect($first)->toHaveCount(2)
        ->and(array_map(sha1(...), $second))->toBe(array_map(sha1(...), $first))
        ->and($second)->toBe($first);
});

it('sorts types and fields by handle, so the order in the blueprint files changes nothing', function (): void {
    $runner = new GeneratorRunner([new TypeScriptTypeHandles, new PhpTypeHandleEnum]);
    $ordered = SchemaFixtures::schema(['a_type' => ['a' => 'text', 'b' => 'text', 'c' => 'text'], 'b_type' => ['x' => 'text'], 'c_type' => ['y' => 'text']]);
    $shuffled = SchemaFixtures::schema(['c_type' => ['y' => 'text'], 'a_type' => ['c' => 'text', 'a' => 'text', 'b' => 'text'], 'b_type' => ['x' => 'text']]);

    $output = contentsOf($runner->run($shuffled, SchemaFixtures::target())->files);

    expect($output)->toBe(contentsOf($runner->run($ordered, SchemaFixtures::target())->files))
        ->and(array_keys($output))->toBe(['app/Cms/Generated/TypeHandle.php', 'resources/js/cms/generated/index.ts']);

    preg_match_all("/case (\\w+) = '/", $output['app/Cms/Generated/TypeHandle.php'], $cases);
    preg_match_all("/^    (\\w+): '/m", $output['resources/js/cms/generated/index.ts'], $fields);

    expect($cases[1])->toBe(['AType', 'BType', 'CType'])
        ->and($fields[1])->toBe(['a', 'b', 'c', 'x', 'y']);
});

it('writes no timestamps, dates or absolute paths', function (): void {
    $output = implode("\n", generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles));

    expect(preg_match('/\d{4}-\d{2}-\d{2}|\d{1,2}:\d{2}|\b\d{10}\b|\b(19|20)\d{2}\b/', $output))->toBe(0)
        ->and($output)->not->toContain('/srv/app')
        ->and($output)->not->toContain(date('Y'));
});

it('names each case after its handle in TitleCase', function (): void {
    $output = contentsOf(new PhpTypeHandleEnum()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'news_item_2' => ['f' => 'text'], 'x9_y' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['app/Cms/Generated/TypeHandle.php'];

    expect($output)->toContain("    case A = 'a';\n    case NewsItem2 = 'news_item_2';\n    case X9Y = 'x9_y';\n");
});

it('refuses handles that give the same enum case, and the handle "class"', function (): void {
    try {
        new PhpTypeHandleEnum()->generate(
            SchemaFixtures::schema(['foo_1' => ['f' => 'text'], 'foo1' => ['f' => 'text'], 'class' => ['f' => 'text']]),
            SchemaFixtures::target(),
        );
        Assert::fail('The generator accepted handles that give no valid enum case.');
    } catch (GenerationFailed $failed) {
        expect($failed->codes())->toBe([GenerateErrorCode::InvalidCaseName, GenerateErrorCode::InvalidCaseName])
            ->and($failed->getMessage())->toContain('Types "foo1" and "foo_1" would both become the enum case "Foo1"')
            ->and($failed->getMessage())->toContain('Type "class" would become the enum case "Class", which PHP reserves');
    }
});

it('keeps a union that fits in Prettier\'s print width on one line, and breaks a longer one per member', function (): void {
    $short = contentsOf(new TypeScriptTypeHandles()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'b' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['resources/js/cms/generated/index.ts'];

    $types = [];

    foreach (range(1, 8) as $number) {
        $types[sprintf('a_fairly_long_type_handle_%d', $number)] = ['f' => 'text'];
    }

    $long = contentsOf(new TypeScriptTypeHandles()->generate(SchemaFixtures::schema($types), SchemaFixtures::target()))['resources/js/cms/generated/index.ts'];

    expect($short)->toContain("export type TypeHandle = 'a' | 'b';\n")
        ->and($long)->toContain("export type TypeHandle =\n  | 'a_fairly_long_type_handle_1'\n  | 'a_fairly_long_type_handle_2'\n")
        ->and($long)->toContain("  | 'a_fairly_long_type_handle_8';\n")
        ->and(max(array_map(strlen(...), explode("\n", $long))))->toBeLessThanOrEqual(TypeScriptTypeHandles::PRINT_WIDTH);
});

it('writes the owner\'s fields by handle and extension fields under ext, by namespace and handle', function (): void {
    $app = SchemaFixtures::root();
    $acme = SchemaFixtures::root('acme', 'vendor/acme/shop/schema');
    $blog = SchemaFixtures::root('blog', 'vendor/acme/blog/schema');
    $product = SchemaFixtures::type($acme, 'product', ['title' => 'text', 'price' => 'decimal']);
    $page = SchemaFixtures::type($acme, 'page', ['title' => 'text']);
    $schema = SchemaResolver::resolve(new Blueprints([$product, $page], [
        SchemaFixtures::extension($blog, 'product.yaml', $product->typeId, ['teaser' => 'long_text']),
        SchemaFixtures::extension($app, 'shop/product.yaml', $product->typeId, ['tax_code' => 'text', 'colour' => 'acme:colour']),
    ]));

    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run($schema, SchemaFixtures::target(roots: [$app, $acme, $blog]))->files);

    expect($output['app/Cms/Generated/TypeHandle.php'])->toContain(<<<'PHP'
            public function fields(): array
            {
                return match ($this) {
                    self::Page => [
                        'title' => 'text',
                    ],
                    self::Product => [
                        'price' => 'decimal',
                        'title' => 'text',
                    ],
                };
            }

            /**
             * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
             * namespace to field handle to field type, sorted by namespace and handle.
             *
             * @return array<string, array<string, string>>
             */
            public function extensionFields(): array
            {
                return match ($this) {
                    self::Page => [],
                    self::Product => [
                        'app' => [
                            'colour' => 'acme:colour',
                            'tax_code' => 'text',
                        ],
                        'blog' => [
                            'teaser' => 'long_text',
                        ],
                    ],
                };
            }
        }

        PHP)
        ->and($output['app/Cms/Generated/TypeHandle.php'])->toContain(" * Schema roots, by owner:\n *   acme: vendor/acme/shop/schema\n *   app: schema\n *   blog: vendor/acme/blog/schema\n")
        ->and($output['resources/js/cms/generated/index.ts'])->toContain(<<<'TS'
        export interface TypeFields {
          page: {
            title: 'text';
          };
          product: {
            price: 'decimal';
            title: 'text';
            ext: {
              app: {
                colour: 'acme:colour';
                tax_code: 'text';
              };
              blog: {
                teaser: 'long_text';
              };
            };
          };
        }

        TS)
        ->and(implode("\n", $output))->not->toContain('ext__');
});

it('writes an enum without cases and never when the schema roots hold no types', function (): void {
    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run(new ResolvedSchema([]), SchemaFixtures::target())->files);

    expect($output)->toBe([
        'app/Cms/Generated/TypeHandle.php' => <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Cms\Generated;

            /**
             * The type handles of the schema roots, with the fields of each type.
             *
             * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
             * this file: change the blueprints and run cms:generate.
             *
             * Schema roots, by owner:
             *   app: schema
             */
            enum TypeHandle: string
            {
                /**
                 * The type's own fields: field handle to field type, sorted by handle.
                 *
                 * @return array<string, string>
                 */
                public function fields(): array
                {
                    return [];
                }

                /**
                 * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
                 * namespace to field handle to field type, sorted by namespace and handle.
                 *
                 * @return array<string, array<string, string>>
                 */
                public function extensionFields(): array
                {
                    return [];
                }
            }

            PHP,
        'resources/js/cms/generated/index.ts' => <<<'TS'
            // The type handles of the schema roots, with the fields of each type.
            //
            // Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
            // this file: change the blueprints and run cms:generate.
            //
            // Schema roots, by owner:
            //   app: schema

            /** The handle of each type in the schema. */
            export type TypeHandle = never;

            /** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */
            export type TypeFields = { [Handle in TypeHandle]: never };

            TS,
    ]);
});

it('writes every core field type through each generator\'s mapping', function (): void {
    $fields = [];

    foreach (CoreFieldType::cases() as $type) {
        $fields['a_'.$type->value] = $type->value;
    }

    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run(SchemaFixtures::schema(['page' => $fields]), SchemaFixtures::target())->files);

    foreach (CoreFieldType::cases() as $type) {
        expect($output['app/Cms/Generated/TypeHandle.php'])->toContain(sprintf("'a_%s' => '%s',", $type->value, PhpTypeHandleEnum::FIELD_TYPES[$type->value]))
            ->and($output['resources/js/cms/generated/index.ts'])->toContain(sprintf("    a_%s: '%s';", $type->value, TypeScriptTypeHandles::FIELD_TYPES[$type->value]));
    }
});

it('refuses a core field type that a generator has no mapping for', function (): void {
    $field = SchemaFixtures::schema(['page' => ['title' => 'text']])->types[0]->fields[0];

    expect(static fn (): string => GeneratedLines::fieldType(PhpTypeHandleEnum::class, ['integer' => 'integer'], $field))
        ->toThrow(GenerationFailed::class, '[generate_invalid_output] '.PhpTypeHandleEnum::class.' has no mapping for the field type "text" of schema/page.yaml, /fields/0.');
});
