<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Tests\Generation;

use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Cbox\Cms\Generators\Generation\Domain\GeneratorRunner;
use Cbox\Cms\Generators\Generation\Domain\Generators\PhpTypeHandleEnum;
use Cbox\Cms\Generators\Generation\Domain\Generators\TypeScriptTypeHandles;
use Cbox\Cms\Generators\Tests\SchemaFixtures;
use PHPUnit\Framework\Assert;

/*
 * The two M0 generators: the PHP enum and the TypeScript union of the type handles. Their output
 * is a pure function of the schema: byte-identical for the same input, sorted whatever order the
 * schema file uses, and without timestamps.
 */

/**
 * @return array<string, string> path to contents
 */
function generatedBy(Generator ...$generators): array
{
    $schema = SchemaFixtures::schema([
        'page' => ['title' => 'text', 'slug' => 'text'],
        'blog_post' => ['title' => 'text', 'body' => 'markdown', 'author' => 'reference'],
    ]);

    return contentsOf(new GeneratorRunner(array_values($generators))->run($schema, SchemaFixtures::target())->files);
}

/**
 * @param  list<GeneratedFile>  $files
 * @return array<string, string>
 */
function contentsOf(array $files): array
{
    $contents = [];

    foreach ($files as $file) {
        $contents[$file->path] = $file->contents;
    }

    return $contents;
}

it('writes a string-backed PHP enum with one case per type and the fields of each type', function (): void {
    expect(generatedBy(new PhpTypeHandleEnum))->toBe(['app/Cms/Generated/TypeHandle.php' => <<<'PHP'
        <?php

        declare(strict_types=1);

        namespace App\Cms\Generated;

        /**
         * The type handles of the fixture schema, with the fields of each type.
         *
         * Generated by cms:generate from the schema below, in format m0-provisional. Do not edit
         * this file: change the schema and run cms:generate.
         *
         * Schema: schema/fixture.yaml
         */
        enum TypeHandle: string
        {
            case BlogPost = 'blog_post';
            case Page = 'page';

            /**
             * The fields of the type: field handle to field type, sorted by field handle.
             *
             * @return array<string, string>
             */
            public function fields(): array
            {
                return match ($this) {
                    self::BlogPost => [
                        'author' => 'reference',
                        'body' => 'markdown',
                        'title' => 'text',
                    ],
                    self::Page => [
                        'slug' => 'text',
                        'title' => 'text',
                    ],
                };
            }
        }

        PHP]);
});

it('writes a TypeScript union of the type handles and an interface of their fields', function (): void {
    expect(generatedBy(new TypeScriptTypeHandles))->toBe(['resources/js/cms/generated/index.ts' => <<<'TS'
        // The type handles of the fixture schema, with the fields of each type.
        //
        // Generated by cms:generate from the schema below, in format m0-provisional. Do not edit
        // this file: change the schema and run cms:generate.
        //
        // Schema: schema/fixture.yaml

        /** The handle of each type in the schema. */
        export type TypeHandle = 'blog_post' | 'page';

        /** The fields of each type: field handle to field type. */
        export interface TypeFields {
          blog_post: {
            author: 'reference';
            body: 'markdown';
            title: 'text';
          };
          page: {
            slug: 'text';
            title: 'text';
          };
        }

        TS]);
});

it('gives byte-identical output for the same input', function (): void {
    $first = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);
    $second = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);

    expect($first)->toHaveCount(2)
        ->and(array_map(sha1(...), $second))->toBe(array_map(sha1(...), $first))
        ->and($second)->toBe($first);
});

it('sorts types and fields by handle, so the order in the schema file changes nothing', function (): void {
    $runner = new GeneratorRunner([new TypeScriptTypeHandles, new PhpTypeHandleEnum]);
    $ordered = SchemaFixtures::schema(['a_type' => ['a' => 'text', 'b' => 'text', 'c' => 'text'], 'b_type' => ['x' => 'text'], 'c_type' => ['y' => 'text']]);
    $shuffled = SchemaFixtures::schema(['c_type' => ['y' => 'text'], 'a_type' => ['c' => 'text', 'a' => 'text', 'b' => 'text'], 'b_type' => ['x' => 'text']]);

    $output = contentsOf($runner->run($shuffled, SchemaFixtures::target())->files);

    expect($output)->toBe(contentsOf($runner->run($ordered, SchemaFixtures::target())->files))
        ->and(array_keys($output))->toBe(['app/Cms/Generated/TypeHandle.php', 'resources/js/cms/generated/index.ts']);

    preg_match_all("/case (\\w+) = '/", $output['app/Cms/Generated/TypeHandle.php'], $cases);
    preg_match_all("/^    (\\w+): '/m", $output['resources/js/cms/generated/index.ts'], $fields);

    expect($cases[1])->toBe(['AType', 'BType', 'CType'])
        ->and($fields[1])->toBe(['a', 'b', 'c', 'x', 'y']);
});

it('writes no timestamps, dates or absolute paths', function (): void {
    $output = implode("\n", generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles));

    expect(preg_match('/\d{4}-\d{2}-\d{2}|\d{1,2}:\d{2}|\b\d{10}\b|\b(19|20)\d{2}\b/', $output))->toBe(0)
        ->and($output)->not->toContain('/srv/app')
        ->and($output)->not->toContain(date('Y'));
});

it('names each case after its handle in TitleCase', function (): void {
    $output = contentsOf(new PhpTypeHandleEnum()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'news_item_2' => ['f' => 'text'], 'x9_y' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['app/Cms/Generated/TypeHandle.php'];

    expect($output)->toContain("    case A = 'a';\n    case NewsItem2 = 'news_item_2';\n    case X9Y = 'x9_y';\n");
});

it('refuses handles that give the same enum case, and the handle "class"', function (): void {
    try {
        new PhpTypeHandleEnum()->generate(
            SchemaFixtures::schema(['foo_1' => ['f' => 'text'], 'foo1' => ['f' => 'text'], 'class' => ['f' => 'text']]),
            SchemaFixtures::target(),
        );
        Assert::fail('The generator accepted handles that give no valid enum case.');
    } catch (GenerationFailed $failed) {
        expect($failed->codes())->toBe([GenerateErrorCode::InvalidCaseName, GenerateErrorCode::InvalidCaseName])
            ->and($failed->getMessage())->toContain('Types "foo1" and "foo_1" would both become the enum case "Foo1"')
            ->and($failed->getMessage())->toContain('Type "class" would become the enum case "Class", which PHP reserves');
    }
});

it('keeps a union that fits in Prettier\'s print width on one line, and breaks a longer one per member', function (): void {
    $short = contentsOf(new TypeScriptTypeHandles()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'b' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['resources/js/cms/generated/index.ts'];

    $types = [];

    foreach (range(1, 8) as $number) {
        $types[sprintf('a_fairly_long_type_handle_%d', $number)] = ['f' => 'text'];
    }

    $long = contentsOf(new TypeScriptTypeHandles()->generate(SchemaFixtures::schema($types), SchemaFixtures::target()))['resources/js/cms/generated/index.ts'];

    expect($short)->toContain("export type TypeHandle = 'a' | 'b';\n")
        ->and($long)->toContain("export type TypeHandle =\n  | 'a_fairly_long_type_handle_1'\n  | 'a_fairly_long_type_handle_2'\n")
        ->and($long)->toContain("  | 'a_fairly_long_type_handle_8';\n")
        ->and(max(array_map(strlen(...), explode("\n", $long))))->toBeLessThanOrEqual(TypeScriptTypeHandles::PRINT_WIDTH);
});
