<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Tests\Generation;

use Cbox\Cms\Generators\Descriptor\Domain\Dto\CompiledSchema;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Cbox\Cms\Generators\Generation\Domain\GeneratorRunner;
use Cbox\Cms\Generators\Generation\Domain\Generators\GeneratedLines;
use Cbox\Cms\Generators\Generation\Domain\Generators\PhpTypeHandleEnum;
use Cbox\Cms\Generators\Generation\Domain\Generators\TypeScriptTypeHandles;
use Cbox\Cms\Generators\Schema\Domain\Dto\Blueprints;
use Cbox\Cms\Generators\Schema\Domain\FieldTypeRegistry;
use Cbox\Cms\Generators\Schema\Domain\FieldTypes\CoreFieldTypes;
use Cbox\Cms\Generators\Tests\SchemaFixtures;
use PHPUnit\Framework\Assert;

/*
 * The two M0 generators: the PHP enum and the TypeScript union of the type handles, with the
 * fields of each type and the extension fields under ext by namespace. Their output is a pure
 * function of the resolved schema: byte-identical for the same input, sorted whatever order the
 * blueprint files use, and without timestamps.
 */

/**
 * @return array<string, string> path to contents
 */
function generatedBy(Generator ...$generators): array
{
    $schema = SchemaFixtures::schema([
        'page' => ['title' => 'text', 'slug' => 'text'],
        'blog_post' => ['title' => 'text', 'body' => 'rich_text', 'author' => 'text'],
    ]);

    return contentsOf(new GeneratorRunner(array_values($generators))->run($schema, SchemaFixtures::target())->files);
}

/**
 * @param  list<GeneratedFile>  $files
 * @return array<string, string>
 */
function contentsOf(array $files): array
{
    $contents = [];

    foreach ($files as $file) {
        $contents[$file->path] = $file->contents;
    }

    return $contents;
}

it('writes a string-backed PHP enum with one case per type and the fields of each type', function (): void {
    expect(generatedBy(new PhpTypeHandleEnum))->toBe(['app/Cms/Generated/TypeHandle.php' => <<<'PHP'
        <?php

        declare(strict_types=1);

        namespace App\Cms\Generated;

        /**
         * The types of the schema roots, named <owner>:<handle>, with the fields of each type.
         *
         * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
         * this file: change the blueprints and run cms:generate.
         *
         * Schema roots, by owner:
         *   app: schema
         */
        enum TypeHandle: string
        {
            case AppBlogPost = 'app:blog_post';
            case AppPage = 'app:page';

            /**
             * The type's own fields: field handle to field type, sorted by handle.
             *
             * @return array<string, string>
             */
            public function fields(): array
            {
                return match ($this) {
                    self::AppBlogPost => [
                        'author' => 'text',
                        'body' => 'rich_text',
                        'title' => 'text',
                    ],
                    self::AppPage => [
                        'slug' => 'text',
                        'title' => 'text',
                    ],
                };
            }

            /**
             * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
             * namespace to field handle to field type, sorted by namespace and handle.
             *
             * @return array<string, array<string, string>>
             */
            public function extensionFields(): array
            {
                return match ($this) {
                    self::AppBlogPost => [],
                    self::AppPage => [],
                };
            }
        }

        PHP]);
});

it('writes a TypeScript union of the type handles and an interface of their fields', function (): void {
    expect(generatedBy(new TypeScriptTypeHandles))->toBe(['resources/js/cms/generated/index.ts' => <<<'TS'
        // The types of the schema roots, named <owner>:<handle>, with the fields of each type.
        //
        // Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
        // this file: change the blueprints and run cms:generate.
        //
        // Schema roots, by owner:
        //   app: schema

        /** Each type in the schema, as <owner>:<handle>. */
        export type TypeHandle = 'app:blog_post' | 'app:page';

        /** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */
        export interface TypeFields {
          'app:blog_post': {
            author: 'text';
            body: 'rich_text';
            title: 'text';
          };
          'app:page': {
            slug: 'text';
            title: 'text';
          };
        }

        TS]);
});

it('gives byte-identical output for the same input', function (): void {
    $first = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);
    $second = generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles);

    expect($first)->toHaveCount(2)
        ->and(array_map(sha1(...), $second))->toBe(array_map(sha1(...), $first))
        ->and($second)->toBe($first);
});

it('sorts types and fields by handle, so the order in the blueprint files changes nothing', function (): void {
    $runner = new GeneratorRunner([new TypeScriptTypeHandles, new PhpTypeHandleEnum]);
    $ordered = SchemaFixtures::schema(['a_type' => ['a' => 'text', 'b' => 'text', 'c' => 'text'], 'b_type' => ['x' => 'text'], 'c_type' => ['y' => 'text']]);
    $shuffled = SchemaFixtures::schema(['c_type' => ['y' => 'text'], 'a_type' => ['c' => 'text', 'a' => 'text', 'b' => 'text'], 'b_type' => ['x' => 'text']]);

    $output = contentsOf($runner->run($shuffled, SchemaFixtures::target())->files);

    expect($output)->toBe(contentsOf($runner->run($ordered, SchemaFixtures::target())->files))
        ->and(array_keys($output))->toBe(['app/Cms/Generated/TypeHandle.php', 'resources/js/cms/generated/index.ts']);

    preg_match_all("/case (\\w+) = '/", $output['app/Cms/Generated/TypeHandle.php'], $cases);
    preg_match_all("/^    (\\w+): '/m", $output['resources/js/cms/generated/index.ts'], $fields);

    expect($cases[1])->toBe(['AppAType', 'AppBType', 'AppCType'])
        ->and($fields[1])->toBe(['a', 'b', 'c', 'x', 'y']);
});

it('writes no timestamps, dates or absolute paths', function (): void {
    $output = implode("\n", generatedBy(new PhpTypeHandleEnum, new TypeScriptTypeHandles));

    expect(preg_match('/\d{4}-\d{2}-\d{2}|\d{1,2}:\d{2}|\b\d{10}\b|\b(19|20)\d{2}\b/', $output))->toBe(0)
        ->and($output)->not->toContain('/srv/app')
        ->and($output)->not->toContain(date('Y'));
});

it('names each case after its owner and handle in TitleCase, with the name <owner>:<handle> as its value', function (): void {
    $output = contentsOf(new PhpTypeHandleEnum()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'news_item_2' => ['f' => 'text'], 'x9_y' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['app/Cms/Generated/TypeHandle.php'];

    expect($output)->toContain("    case AppA = 'app:a';\n    case AppNewsItem2 = 'app:news_item_2';\n    case AppX9Y = 'app:x9_y';\n");
});

it('generates the same type handle from two owners as two types, and adding one leaves the other\'s names as they were', function (): void {
    $app = SchemaFixtures::root();
    $acme = SchemaFixtures::root('acme', 'vendor/acme/shop/schema');
    $appProduct = SchemaFixtures::type($app, 'product', ['tax_code' => 'text']);
    $acmeProduct = SchemaFixtures::type($acme, 'product', ['sku' => 'text']);
    $runner = new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles]);

    $before = contentsOf($runner->run(SchemaFixtures::compiled(new Blueprints([$appProduct], [])), SchemaFixtures::target(roots: [$app, $acme]))->files);
    $after = contentsOf($runner->run(SchemaFixtures::compiled(new Blueprints([$appProduct, $acmeProduct], [])), SchemaFixtures::target(roots: [$app, $acme]))->files);

    expect($after['app/Cms/Generated/TypeHandle.php'])->toContain(<<<'PHP'
            case AcmeProduct = 'acme:product';
            case AppProduct = 'app:product';

        PHP)
        ->and($after['app/Cms/Generated/TypeHandle.php'])->toContain(<<<'PHP'
                    self::AcmeProduct => [
                        'sku' => 'text',
                    ],
                    self::AppProduct => [
                        'tax_code' => 'text',
                    ],
        PHP)
        ->and($after['resources/js/cms/generated/index.ts'])->toContain(<<<'TS'
        export type TypeHandle = 'acme:product' | 'app:product';

        /** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */
        export interface TypeFields {
          'acme:product': {
            sku: 'text';
          };
          'app:product': {
            tax_code: 'text';
          };
        }

        TS)
        ->and($before['app/Cms/Generated/TypeHandle.php'])->toContain("    case AppProduct = 'app:product';\n")
        ->and($before['resources/js/cms/generated/index.ts'])->toContain("export type TypeHandle = 'app:product';\n");
});

it('never gives the types of two owners the same enum case', function (): void {
    $owners = ['a', 'ab', 'a1', 'a1b', 'app', 'appa', 'acme', 'c', 'cl'];
    $handles = ['a', 'b', 'ab', 'a_b', 'b_a', 'a1', 'a_1', 'a1_b', 'app_b', 'acme_product', 'product', 'lass', 'ass'];
    $cases = [];

    foreach ($owners as $owner) {
        foreach ($handles as $handle) {
            $case = PhpTypeHandleEnum::caseName(SchemaFixtures::schema([$handle => ['f' => 'text']], $owner)->types[0]);

            expect($case)->toStartWith(ucfirst($owner))
                ->and(ctype_upper(substr($case, strlen($owner), 1)))->toBeTrue()
                ->and(preg_match('/\A[A-Z][a-z0-9]*[A-Z]/', $case))->toBe(1);

            $cases[$case][$owner] = true;
        }
    }

    expect(array_filter($cases, static fn (array $owners): bool => count($owners) > 1))->toBe([]);
});

it('refuses handles of one owner that give the same enum case, and a type whose case reads "class"', function (): void {
    try {
        new PhpTypeHandleEnum()->generate(
            SchemaFixtures::schema(['foo_1' => ['f' => 'text'], 'foo1' => ['f' => 'text']]),
            SchemaFixtures::target(),
        );
        Assert::fail('The generator accepted handles that give the same enum case.');
    } catch (GenerationFailed $failed) {
        expect($failed->codes())->toBe([GenerateErrorCode::InvalidCaseName])
            ->and($failed->problems[0]->message)->toBe('schema/foo_1.yaml, /handle: the types "app:foo1" (schema/foo1.yaml, /handle) and "app:foo_1" would both become the enum case "AppFoo1". Choose handles that differ in more than underscores.');
    }

    try {
        new PhpTypeHandleEnum()->generate(SchemaFixtures::schema(['lass' => ['f' => 'text']], 'c'), SchemaFixtures::target());
        Assert::fail('The generator accepted a type whose enum case PHP reserves.');
    } catch (GenerationFailed $failed) {
        expect($failed->codes())->toBe([GenerateErrorCode::InvalidCaseName])
            ->and($failed->problems[0]->message)->toBe('schema/lass.yaml, /handle: the type "c:lass" would become the enum case "CLass", which PHP reserves. Choose another handle.');
    }
});

it('keeps a union that fits in Prettier\'s print width on one line, and breaks a longer one per member', function (): void {
    $short = contentsOf(new TypeScriptTypeHandles()->generate(
        SchemaFixtures::schema(['a' => ['f' => 'text'], 'b' => ['f' => 'text']]),
        SchemaFixtures::target(),
    ))['resources/js/cms/generated/index.ts'];

    $types = [];

    foreach (range(1, 8) as $number) {
        $types[sprintf('a_fairly_long_type_handle_%d', $number)] = ['f' => 'text'];
    }

    $long = contentsOf(new TypeScriptTypeHandles()->generate(SchemaFixtures::schema($types), SchemaFixtures::target()))['resources/js/cms/generated/index.ts'];

    expect($short)->toContain("export type TypeHandle = 'app:a' | 'app:b';\n")
        ->and($long)->toContain("export type TypeHandle =\n  | 'app:a_fairly_long_type_handle_1'\n  | 'app:a_fairly_long_type_handle_2'\n")
        ->and($long)->toContain("  | 'app:a_fairly_long_type_handle_8';\n")
        ->and(max(array_map(strlen(...), explode("\n", $long))))->toBeLessThanOrEqual(TypeScriptTypeHandles::PRINT_WIDTH);
});

it('writes the owner\'s fields by handle and extension fields under ext, by namespace and handle', function (): void {
    $app = SchemaFixtures::root();
    $acme = SchemaFixtures::root('acme', 'vendor/acme/shop/schema');
    $blog = SchemaFixtures::root('blog', 'vendor/acme/blog/schema');
    $product = SchemaFixtures::type($acme, 'product', ['title' => 'text', 'price' => 'decimal']);
    $page = SchemaFixtures::type($acme, 'page', ['title' => 'text']);
    $schema = SchemaFixtures::compiled(new Blueprints([$product, $page], [
        SchemaFixtures::extension($blog, 'product.yaml', $product->typeId, ['teaser' => 'long_text']),
        SchemaFixtures::extension($app, 'shop/product.yaml', $product->typeId, ['tax_code' => 'text', 'colour' => 'select']),
    ]));

    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run($schema, SchemaFixtures::target(roots: [$app, $acme, $blog]))->files);

    expect($output['app/Cms/Generated/TypeHandle.php'])->toContain(<<<'PHP'
            public function fields(): array
            {
                return match ($this) {
                    self::AcmePage => [
                        'title' => 'text',
                    ],
                    self::AcmeProduct => [
                        'price' => 'decimal',
                        'title' => 'text',
                    ],
                };
            }

            /**
             * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
             * namespace to field handle to field type, sorted by namespace and handle.
             *
             * @return array<string, array<string, string>>
             */
            public function extensionFields(): array
            {
                return match ($this) {
                    self::AcmePage => [],
                    self::AcmeProduct => [
                        'app' => [
                            'colour' => 'select',
                            'tax_code' => 'text',
                        ],
                        'blog' => [
                            'teaser' => 'long_text',
                        ],
                    ],
                };
            }
        }

        PHP)
        ->and($output['app/Cms/Generated/TypeHandle.php'])->toContain(" * Schema roots, by owner:\n *   acme: vendor/acme/shop/schema\n *   app: schema\n *   blog: vendor/acme/blog/schema\n")
        ->and($output['resources/js/cms/generated/index.ts'])->toContain(<<<'TS'
        export interface TypeFields {
          'acme:page': {
            title: 'text';
          };
          'acme:product': {
            price: 'decimal';
            title: 'text';
            ext: {
              app: {
                colour: 'select';
                tax_code: 'text';
              };
              blog: {
                teaser: 'long_text';
              };
            };
          };
        }

        TS)
        ->and(implode("\n", $output))->not->toContain('ext__');
});

it('writes an enum without cases and never when the schema roots hold no types', function (): void {
    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run(new CompiledSchema([]), SchemaFixtures::target())->files);

    expect($output)->toBe([
        'app/Cms/Generated/TypeHandle.php' => <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Cms\Generated;

            /**
             * The types of the schema roots, named <owner>:<handle>, with the fields of each type.
             *
             * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
             * this file: change the blueprints and run cms:generate.
             *
             * Schema roots, by owner:
             *   app: schema
             */
            enum TypeHandle: string
            {
                /**
                 * The type's own fields: field handle to field type, sorted by handle.
                 *
                 * @return array<string, string>
                 */
                public function fields(): array
                {
                    return [];
                }

                /**
                 * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:
                 * namespace to field handle to field type, sorted by namespace and handle.
                 *
                 * @return array<string, array<string, string>>
                 */
                public function extensionFields(): array
                {
                    return [];
                }
            }

            PHP,
        'resources/js/cms/generated/index.ts' => <<<'TS'
            // The types of the schema roots, named <owner>:<handle>, with the fields of each type.
            //
            // Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit
            // this file: change the blueprints and run cms:generate.
            //
            // Schema roots, by owner:
            //   app: schema

            /** Each type in the schema, as <owner>:<handle>. */
            export type TypeHandle = never;

            /** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */
            export type TypeFields = { [Handle in TypeHandle]: never };

            TS,
    ]);
});

it('writes every core field type through each generator\'s mapping', function (): void {
    $fields = [];

    foreach (new FieldTypeRegistry(new CoreFieldTypes)->names() as $type) {
        $fields['a_'.$type] = $type;
    }

    $output = contentsOf(new GeneratorRunner([new PhpTypeHandleEnum, new TypeScriptTypeHandles])->run(SchemaFixtures::schema(['page' => $fields]), SchemaFixtures::target())->files);

    foreach (new FieldTypeRegistry(new CoreFieldTypes)->names() as $type) {
        expect($output['app/Cms/Generated/TypeHandle.php'])->toContain(sprintf("'a_%s' => '%s',", $type, PhpTypeHandleEnum::FIELD_TYPES[$type]))
            ->and($output['resources/js/cms/generated/index.ts'])->toContain(sprintf("    a_%s: '%s';", $type, TypeScriptTypeHandles::FIELD_TYPES[$type]));
    }
});

it('refuses a core field type that a generator has no mapping for', function (): void {
    $field = SchemaFixtures::schema(['page' => ['title' => 'text']])->types[0]->fields[0];

    expect(static fn (): string => GeneratedLines::fieldType(PhpTypeHandleEnum::class, ['integer' => 'integer'], $field))
        ->toThrow(GenerationFailed::class, '[generate_invalid_output] '.PhpTypeHandleEnum::class.' has no mapping for the field type "text" of schema/page.yaml, /fields/0.');
});
