<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;

/**
 * What the PHP generators of the type chain write alike: names from handles, string literals,
 * comment text and the frame of a file, formatted the way Pint, Rector and PHPStan level 10 accept
 * it unchanged.
 */
#[Internal]
final readonly class PhpSource
{
    /**
     * The lines every generated PHP file carries in its first docblock.
     *
     * @var list<string>
     */
    public const array NOTICE = [
        'Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
        'this file: change the blueprints and run cms:generate.',
    ];

    /** The width of a docblock's text, so a line with its ` * ` stays within 100 characters. */
    private const int DOC_WIDTH = 96;

    /**
     * The docblock of a generated class: each paragraph of the summary wrapped at 100 characters,
     * then the notice.
     *
     * @param  list<string>  $summary  the paragraphs
     * @return list<string>
     */
    public static function docblock(array $summary): array
    {
        $lines = [];

        foreach ($summary as $paragraph) {
            if ($lines !== []) {
                $lines[] = ' *';
            }

            foreach (explode("\n", wordwrap($paragraph, self::DOC_WIDTH)) as $line) {
                $lines[] = ' * '.$line;
            }
        }

        return [
            '/**',
            ...$lines,
            ' *',
            ...array_map(static fn (string $line): string => ' * '.$line, self::NOTICE),
            ' */',
        ];
    }

    /**
     * A snake_case handle in StudlyCaps, such as `launch_date` to `LaunchDate`.
     */
    public static function studly(string $handle): string
    {
        return str_replace('_', '', ucwords($handle, '_'));
    }

    /**
     * A snake_case handle in camelCase, such as `launch_date` to `launchDate`.
     */
    public static function camel(string $handle): string
    {
        return lcfirst(self::studly($handle));
    }

    /**
     * A single-quoted PHP string literal of the text.
     */
    public static function literal(string $text): string
    {
        return "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $text)."'";
    }

    /**
     * Text from a blueprint on one line of a docblock: line breaks become spaces, and nothing in it
     * ends the comment.
     */
    public static function comment(string $text): string
    {
        return str_replace('*/', '*\\/', trim((string) preg_replace('/\s+/', ' ', $text)));
    }

    /**
     * A PHP file of the namespace: the imports that the lines use, sorted as Pint sorts them, then
     * the lines.
     *
     * @param  list<string>  $imports  fully qualified class names the lines may use
     * @param  list<string>  $lines
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    public static function file(string $path, string $namespace, array $imports, array $lines): GeneratedFile
    {
        $body = implode("\n", $lines);
        $imports = array_values(array_filter(
            array_unique($imports),
            static fn (string $import): bool => preg_match('/(?<![\\\\\w$])'.preg_quote(self::shortName($import), '/').'\b/', $body) === 1,
        ));
        usort($imports, static fn (string $a, string $b): int => strcmp(self::sortKey($a), self::sortKey($b)));

        return new GeneratedFile($path, implode("\n", [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace '.$namespace.';',
            '',
            ...($imports === [] ? [] : [...array_map(static fn (string $import): string => 'use '.$import.';', $imports), '']),
            ...$lines,
        ])."\n");
    }

    /**
     * The name of a class without its namespace.
     */
    public static function shortName(string $class): string
    {
        $separator = strrpos($class, '\\');

        return $separator === false ? $class : substr($class, $separator + 1);
    }

    private static function sortKey(string $import): string
    {
        return strtolower(str_replace('\\', ' ', $import));
    }
}
