<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationProblem;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedField;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedSchema;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedType;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Override;

/**
 * The M0 PHP link of the type chain: a string-backed enum `TypeHandle` with one case per type, and
 * `fields()` that maps each field name of the type to its field type. The case name is the handle
 * in TitleCase: `blog_post` becomes `BlogPost`. An extension field is named by its column name,
 * `ext__<namespace>__<handle>`. Without types the enum has no cases, and `fields()` returns an
 * empty array, because a match over an enum without cases handles no value.
 *
 * The output is formatted the way Pint, Rector and PHPStan level 10 accept it unchanged.
 */
#[Internal]
final readonly class PhpTypeHandleEnum implements Generator
{
    public const string CLASS_NAME = 'TypeHandle';

    /**
     * What `fields()` gives for each core field type of the blueprint schema v1: its name. An
     * addon's field type is given as its `<namespace>:<handle>`. The generator-coverage test holds
     * the keys to the field types of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array FIELD_TYPES = [
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'decimal' => 'decimal',
        'group' => 'group',
        'integer' => 'integer',
        'long_text' => 'long_text',
        'rich_text' => 'rich_text',
        'select' => 'select',
        'text' => 'text',
    ];

    /**
     * What the enum holds for a blueprint file of each kind. The generator-coverage test holds the
     * keys to the kinds of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array KINDS = [
        'extension' => 'its fields in the fields() arm of the type it extends, named ext__<namespace>__<handle>',
        'type' => 'a case named after the handle, and an arm of fields() with the type\'s own fields',
    ];

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->phpDirectory;
    }

    #[Override]
    public function generate(ResolvedSchema $schema, GenerationTarget $target): array
    {
        $this->assertCaseNames($schema);

        $cases = array_map(
            static fn (ResolvedType $type): string => sprintf("    case %s = '%s';", self::caseName($type), $type->handle()),
            $schema->types,
        );

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace '.$target->phpNamespace.';',
            '',
            '/**',
            ' * The type handles of the schema roots, with the fields of each type.',
            ' *',
            ' * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
            ' * this file: change the blueprints and run cms:generate.',
            ' *',
            ' * Schema roots, by owner:',
            ...GeneratedLines::schemaRoots($target, ' *   '),
            ' */',
            'enum '.self::CLASS_NAME.': string',
            '{',
            ...($cases === [] ? [] : [...$cases, '']),
            '    /**',
            '     * The fields of the type: field name to field type, sorted by name. An extension field is',
            '     * named by its column, ext__<namespace>__<handle>.',
            '     *',
            '     * @return array<string, string>',
            '     */',
            '    public function fields(): array',
            '    {',
            ...($cases === [] ? ['        return [];'] : [
                '        return match ($this) {',
                ...array_merge(...array_map($this->fieldsArm(...), $schema->types)),
                '        };',
            ]),
            '    }',
            '}',
        ];

        return [new GeneratedFile(
            $target->phpDirectory.'/'.self::CLASS_NAME.'.php',
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * The enum case of a type: its handle in TitleCase.
     */
    private static function caseName(ResolvedType $type): string
    {
        return str_replace('_', '', ucwords($type->handle(), '_'));
    }

    /**
     * Every type gets a case name PHP accepts, and no two types get the same one.
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidCaseName
     */
    private function assertCaseNames(ResolvedSchema $schema): void
    {
        $handles = [];
        $problems = [];

        foreach ($schema->types as $type) {
            $handle = $type->handle();
            $case = self::caseName($type);

            if (strtolower($case) === 'class') {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    'Type "%s" would become the enum case "%s", which PHP reserves. Choose another handle.',
                    $handle,
                    $case,
                ));
            }

            if (isset($handles[$case])) {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    'Types "%s" and "%s" would both become the enum case "%s". Choose handles that differ in more than underscores.',
                    $handles[$case],
                    $handle,
                    $case,
                ));
            }

            $handles[$case] = $handle;
        }

        if ($problems !== []) {
            throw GenerationFailed::with($problems);
        }
    }

    /**
     * @return list<string>
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldsArm(ResolvedType $type): array
    {
        $lines = ['            self::'.self::caseName($type).' => ['];

        foreach ($type->fields as $field) {
            $lines[] = sprintf("                '%s' => '%s',", $field->name, $this->fieldType($field));
        }

        $lines[] = '            ],';

        return $lines;
    }

    /**
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldType(ResolvedField $field): string
    {
        return $field->hasAddonType()
            ? $field->typeName()
            : GeneratedLines::fieldType(self::class, self::FIELD_TYPES, $field);
    }
}
