<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\CompiledSchema;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\FieldDescriptor;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\TypeDescriptor;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationProblem;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Override;

/**
 * The M0 PHP link of the type chain: a string-backed enum `TypeHandle` with one case per type,
 * `fields()` that maps each handle of the owner's fields to its field type, and `extensionFields()`
 * that maps the namespace of each extender to its fields, handle to field type, the way PHP
 * addresses an extension field as `ext->app->taxCode` (PRD 11.12); the column name
 * `ext__<namespace>__<handle>` belongs to the type table alone. A type is named by its owner and
 * handle, because a handle is unique only for its owner: the value of its case is
 * `<owner>:<handle>` (TypeDescriptor::name()), and the case name is the owner and the handle in
 * TitleCase, so `blog_post` of `app` is `AppBlogPost = 'app:blog_post'` and `product` of `acme` is
 * `AcmeProduct = 'acme:product'`. An owner is a lowercase letter followed by lowercase letters and
 * digits, so the owner's part of a case name ends where the second capital letter begins, and the
 * types of two owners never share a case name. Without types the enum has no cases, and both
 * methods return an empty array, because a match over an enum without cases handles no value.
 *
 * The output is formatted the way Pint, Rector and PHPStan level 10 accept it unchanged.
 */
#[Internal]
final readonly class PhpTypeHandleEnum implements Generator
{
    public const string CLASS_NAME = 'TypeHandle';

    /**
     * What `fields()` gives for each core field type of the blueprint schema v1: its name. A field
     * type without a mapping here is refused as invalid output. The generator-coverage test holds
     * the keys to the field types of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array FIELD_TYPES = [
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'decimal' => 'decimal',
        'group' => 'group',
        'integer' => 'integer',
        'long_text' => 'long_text',
        'rich_text' => 'rich_text',
        'select' => 'select',
        'text' => 'text',
    ];

    /**
     * What the enum holds for a blueprint file of each kind. The generator-coverage test holds the
     * keys to the kinds of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array KINDS = [
        'extension' => 'its fields in the extensionFields() arm of the type it extends, under its namespace',
        'type' => 'a case named after the owner and the handle, an arm of fields() with the type\'s own fields and an arm of extensionFields()',
    ];

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->phpDirectory;
    }

    #[Override]
    public function generate(CompiledSchema $schema, GenerationTarget $target): array
    {
        self::assertCaseNames($schema);

        $cases = array_map(
            static fn (TypeDescriptor $type): string => sprintf("    case %s = '%s';", self::caseName($type), $type->name()),
            $schema->types,
        );

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace '.$target->phpNamespace.';',
            '',
            '/**',
            ' * The types of the schema roots, named <owner>:<handle>, with the fields of each type.',
            ' *',
            ' * Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
            ' * this file: change the blueprints and run cms:generate.',
            ' *',
            ' * Schema roots, by owner:',
            ...GeneratedLines::schemaRoots($target, ' *   '),
            ' */',
            'enum '.self::CLASS_NAME.': string',
            '{',
            ...($cases === [] ? [] : [...$cases, '']),
            '    /**',
            "     * The type's own fields: field handle to field type, sorted by handle.",
            '     *',
            '     * @return array<string, string>',
            '     */',
            '    public function fields(): array',
            '    {',
            ...($cases === [] ? ['        return [];'] : [
                '        return match ($this) {',
                ...array_merge(...array_map($this->fieldsArm(...), $schema->types)),
                '        };',
            ]),
            '    }',
            '',
            '    /**',
            '     * The fields that extensions add to the type, addressed as ext.<namespace>.<handle>:',
            '     * namespace to field handle to field type, sorted by namespace and handle.',
            '     *',
            '     * @return array<string, array<string, string>>',
            '     */',
            '    public function extensionFields(): array',
            '    {',
            ...($cases === [] ? ['        return [];'] : [
                '        return match ($this) {',
                ...array_merge(...array_map($this->extensionFieldsArm(...), $schema->types)),
                '        };',
            ]),
            '    }',
            '}',
        ];

        return [new GeneratedFile(
            $target->phpDirectory.'/'.self::CLASS_NAME.'.php',
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * The enum case of a type: its owner and its handle in TitleCase.
     */
    public static function caseName(TypeDescriptor $type): string
    {
        return ucfirst($type->owner->value).str_replace('_', '', ucwords($type->handle->value, '_'));
    }

    /**
     * Every type gets a case name PHP accepts, and no two types get the same one. Only two types of
     * one owner can: handles that differ only in underscores before a digit, such as `foo_1` and
     * `foo1`.
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidCaseName
     */
    public static function assertCaseNames(CompiledSchema $schema): void
    {
        $types = [];
        $problems = [];

        foreach ($schema->types as $type) {
            $case = self::caseName($type);

            if (strtolower($case) === 'class') {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    '%s: the type "%s" would become the enum case "%s", which PHP reserves. Choose another handle.',
                    $type->location->below('handle')->describe(),
                    $type->name(),
                    $case,
                ));
            }

            if (isset($types[$case])) {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    '%s: the types "%s" (%s) and "%s" would both become the enum case "%s". Choose handles that differ in more than underscores.',
                    $type->location->below('handle')->describe(),
                    $types[$case]->name(),
                    $types[$case]->location->below('handle')->describe(),
                    $type->name(),
                    $case,
                ));
            }

            $types[$case] ??= $type;
        }

        if ($problems !== []) {
            throw GenerationFailed::with($problems);
        }
    }

    /**
     * @return list<string>
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldsArm(TypeDescriptor $type): array
    {
        $lines = ['            self::'.self::caseName($type).' => ['];

        foreach ($type->ownFields() as $field) {
            $lines[] = sprintf("                '%s' => '%s',", $field->handle->value, $this->fieldType($field));
        }

        $lines[] = '            ],';

        return $lines;
    }

    /**
     * @return list<string>
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function extensionFieldsArm(TypeDescriptor $type): array
    {
        $extensions = $type->extensionFields();

        if ($extensions === []) {
            return ['            self::'.self::caseName($type).' => [],'];
        }

        $lines = ['            self::'.self::caseName($type).' => ['];

        foreach ($extensions as $namespace => $fields) {
            $lines[] = "                '".$namespace."' => [";

            foreach ($fields as $field) {
                $lines[] = sprintf("                    '%s' => '%s',", $field->handle->value, $this->fieldType($field));
            }

            $lines[] = '                ],';
        }

        $lines[] = '            ],';

        return $lines;
    }

    /**
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldType(FieldDescriptor $field): string
    {
        return GeneratedLines::fieldType(self::class, self::FIELD_TYPES, $field);
    }
}
