<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationProblem;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\GenerateErrorCode;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Cbox\Cms\Generators\Schema\Domain\FixtureSchema;
use Cbox\Cms\Generators\Schema\Domain\TypeDefinition;
use Override;

/**
 * The M0 PHP link of the type chain: a string-backed enum `TypeHandle` with one case per type,
 * and `fields()` that maps each field handle to its field type. The case name is the handle in
 * TitleCase: `blog_post` becomes `BlogPost`.
 *
 * The output is formatted the way Pint, Rector and PHPStan level 10 accept it unchanged.
 */
#[Internal]
final readonly class PhpTypeHandleEnum implements Generator
{
    public const string CLASS_NAME = 'TypeHandle';

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->phpDirectory;
    }

    #[Override]
    public function generate(FixtureSchema $schema, GenerationTarget $target): array
    {
        $this->assertCaseNames($schema);

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace '.$target->phpNamespace.';',
            '',
            '/**',
            ' * The type handles of the fixture schema, with the fields of each type.',
            ' *',
            ' * Generated by cms:generate from the schema below, in format '.FixtureSchema::FORMAT.'. Do not edit',
            ' * this file: change the schema and run cms:generate.',
            ' *',
            ' * Schema: '.$target->schema,
            ' */',
            'enum '.self::CLASS_NAME.': string',
            '{',
            ...array_map(
                static fn (TypeDefinition $type): string => sprintf("    case %s = '%s';", self::caseName($type), $type->handle->value),
                $schema->types,
            ),
            '',
            '    /**',
            '     * The fields of the type: field handle to field type, sorted by field handle.',
            '     *',
            '     * @return array<string, string>',
            '     */',
            '    public function fields(): array',
            '    {',
            '        return match ($this) {',
            ...array_merge(...array_map($this->fieldsArm(...), $schema->types)),
            '        };',
            '    }',
            '}',
        ];

        return [new GeneratedFile(
            $target->phpDirectory.'/'.self::CLASS_NAME.'.php',
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * The enum case of a type: its handle in TitleCase.
     */
    private static function caseName(TypeDefinition $type): string
    {
        return str_replace('_', '', ucwords($type->handle->value, '_'));
    }

    /**
     * Every type gets a case name PHP accepts, and no two types get the same one.
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidCaseName
     */
    private function assertCaseNames(FixtureSchema $schema): void
    {
        $handles = [];
        $problems = [];

        foreach ($schema->types as $type) {
            $handle = $type->handle->value;
            $case = self::caseName($type);

            if (strtolower($case) === 'class') {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    'Type "%s" would become the enum case "%s", which PHP reserves. Choose another handle.',
                    $handle,
                    $case,
                ));
            }

            if (isset($handles[$case])) {
                $problems[] = new GenerationProblem(GenerateErrorCode::InvalidCaseName, sprintf(
                    'Types "%s" and "%s" would both become the enum case "%s". Choose handles that differ in more than underscores.',
                    $handles[$case],
                    $handle,
                    $case,
                ));
            }

            $handles[$case] = $handle;
        }

        if ($problems !== []) {
            throw GenerationFailed::with($problems);
        }
    }

    /**
     * @return list<string>
     */
    private function fieldsArm(TypeDefinition $type): array
    {
        $lines = ['            self::'.self::caseName($type).' => ['];

        foreach ($type->fields as $field) {
            $lines[] = sprintf("                '%s' => '%s',", $field->handle->value, $field->type->value);
        }

        $lines[] = '            ],';

        return $lines;
    }
}
