<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedField;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedSchema;
use Cbox\Cms\Generators\Generation\Domain\Dto\ResolvedType;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Override;

/**
 * The M0 TypeScript link of the type chain, in `index.ts`: the union type `TypeHandle` of the
 * type handles, and the interface `TypeFields` that maps each type to its fields and their field
 * types. An extension field is named by its column name, `ext__<namespace>__<handle>`. Without
 * types, `TypeHandle` is `never` and `TypeFields` the mapped type over it, which has no keys; an
 * empty interface would accept any value that is not null.
 *
 * The output is formatted the way the shared Prettier configuration prints it (printWidth 100,
 * single quotes), so `prettier --check` accepts it unchanged. A union that fits on one line stays
 * on one line; a longer one gets one member per line with a leading `|`, as Prettier breaks it.
 */
#[Internal]
final readonly class TypeScriptTypeHandles implements Generator
{
    public const string FILE_NAME = 'index.ts';

    /** Prettier's printWidth in js/tooling/prettier.js. */
    public const int PRINT_WIDTH = 100;

    /**
     * The string literal type `TypeFields` gives for each core field type of the blueprint schema
     * v1: its name. An addon's field type is given as its `<namespace>:<handle>`. The
     * generator-coverage test holds the keys to the field types of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array FIELD_TYPES = [
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'decimal' => 'decimal',
        'group' => 'group',
        'integer' => 'integer',
        'long_text' => 'long_text',
        'rich_text' => 'rich_text',
        'select' => 'select',
        'text' => 'text',
    ];

    /**
     * What the file holds for a blueprint file of each kind. The generator-coverage test holds the
     * keys to the kinds of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array KINDS = [
        'extension' => 'its fields in the TypeFields entry of the type it extends, named ext__<namespace>__<handle>',
        'type' => 'a member of TypeHandle, and an entry of TypeFields with the type\'s own fields',
    ];

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->typeScriptDirectory;
    }

    #[Override]
    public function generate(ResolvedSchema $schema, GenerationTarget $target): array
    {
        $lines = [
            '// The type handles of the schema roots, with the fields of each type.',
            '//',
            '// Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
            '// this file: change the blueprints and run cms:generate.',
            '//',
            '// Schema roots, by owner:',
            ...GeneratedLines::schemaRoots($target, '//   '),
            '',
            '/** The handle of each type in the schema. */',
            ...$this->union($schema),
            '',
            '/** The fields of each type: field name to field type. */',
            ...($schema->types === [] ? ['export type TypeFields = { [Handle in TypeHandle]: never };'] : [
                'export interface TypeFields {',
                ...array_merge(...array_map($this->fields(...), $schema->types)),
                '}',
            ]),
        ];

        return [new GeneratedFile(
            $target->typeScriptDirectory.'/'.self::FILE_NAME,
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * @return list<string>
     */
    private function union(ResolvedSchema $schema): array
    {
        $members = array_map(static fn (ResolvedType $type): string => "'".$type->handle()."'", $schema->types);
        $declaration = 'export type TypeHandle =';
        $line = $declaration.' '.($members === [] ? 'never' : implode(' | ', $members)).';';

        if (strlen($line) <= self::PRINT_WIDTH) {
            return [$line];
        }

        $lines = [$declaration];

        foreach ($members as $member) {
            $lines[] = '  | '.$member;
        }

        $lines[] = array_pop($lines).';';

        return $lines;
    }

    /**
     * @return list<string>
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fields(ResolvedType $type): array
    {
        $lines = ['  '.$type->handle().': {'];

        foreach ($type->fields as $field) {
            $lines[] = sprintf("    %s: '%s';", $field->name, $this->fieldType($field));
        }

        $lines[] = '  };';

        return $lines;
    }

    /**
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldType(ResolvedField $field): string
    {
        return $field->hasAddonType()
            ? $field->typeName()
            : GeneratedLines::fieldType(self::class, self::FIELD_TYPES, $field);
    }
}
