<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Cbox\Cms\Generators\Schema\Domain\FixtureSchema;
use Cbox\Cms\Generators\Schema\Domain\TypeDefinition;
use Override;

/**
 * The M0 TypeScript link of the type chain, in `index.ts`: the union type `TypeHandle` of the
 * type handles, and the interface `TypeFields` that maps each type to its fields and their field
 * types.
 *
 * The output is formatted the way the shared Prettier configuration prints it (printWidth 100,
 * single quotes), so `prettier --check` accepts it unchanged. A union that fits on one line stays
 * on one line; a longer one gets one member per line with a leading `|`, as Prettier breaks it.
 */
#[Internal]
final readonly class TypeScriptTypeHandles implements Generator
{
    public const string FILE_NAME = 'index.ts';

    /** Prettier's printWidth in js/tooling/prettier.js. */
    public const int PRINT_WIDTH = 100;

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->typeScriptDirectory;
    }

    #[Override]
    public function generate(FixtureSchema $schema, GenerationTarget $target): array
    {
        $lines = [
            '// The type handles of the fixture schema, with the fields of each type.',
            '//',
            '// Generated by cms:generate from the schema below, in format '.FixtureSchema::FORMAT.'. Do not edit',
            '// this file: change the schema and run cms:generate.',
            '//',
            '// Schema: '.$target->schema,
            '',
            '/** The handle of each type in the schema. */',
            ...$this->union($schema),
            '',
            '/** The fields of each type: field handle to field type. */',
            'export interface TypeFields {',
            ...array_merge(...array_map($this->fields(...), $schema->types)),
            '}',
        ];

        return [new GeneratedFile(
            $target->typeScriptDirectory.'/'.self::FILE_NAME,
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * @return list<string>
     */
    private function union(FixtureSchema $schema): array
    {
        $members = array_map(static fn (TypeDefinition $type): string => "'".$type->handle->value."'", $schema->types);
        $declaration = 'export type TypeHandle =';
        $line = $declaration.' '.implode(' | ', $members).';';

        if (strlen($line) <= self::PRINT_WIDTH) {
            return [$line];
        }

        $lines = [$declaration];

        foreach ($members as $member) {
            $lines[] = '  | '.$member;
        }

        $lines[] = array_pop($lines).';';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function fields(TypeDefinition $type): array
    {
        $lines = ['  '.$type->handle->value.': {'];

        foreach ($type->fields as $field) {
            $lines[] = sprintf("    %s: '%s';", $field->handle->value, $field->type->value);
        }

        $lines[] = '  };';

        return $lines;
    }
}
