<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Codec\Domain\Dto\CodecContract;
use Cbox\Cms\Generators\Codec\Domain\RecordContracts;
use Cbox\Cms\Generators\Codec\Domain\TypeScriptEmitter;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\CompiledSchema;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Closure;
use Override;

/**
 * The TypeScript link of the contracts (PRD 11.12, GUARDRAILS 2.2): in the TypeScript directory, the
 * runtime module `validation.ts`, and one module per contract version (TypeScriptEmitter) with its
 * JSON form as TypeScript types and its runtime validator:
 *
 * - `records/<Owner><Handle>V1.ts` for the record of each type (RecordContracts), with snake_case
 *   keys, the extension fields under `ext.<namespace>.<handle>` and rich text as Portable Text;
 * - `protocol/<Name>V<version>.ts` for each of the kernel's JSON Schemas, such as the receipt, the
 *   problem details and the envelope, whose contracts it is given.
 *
 * The runtime module and the kernel's contracts come from cboxdk/cms, which the generator is given
 * as closures, so it stays a pure function of what they give and of the schema; they are called
 * when it generates.
 */
#[Internal]
final readonly class TypeScriptContracts implements Generator
{
    /** The runtime module, below the TypeScript directory. */
    public const string RUNTIME = 'validation.ts';

    /** The directory of the records' modules, below the TypeScript directory. */
    public const string RECORDS = 'records';

    /** The directory of the kernel's contracts' modules, below the TypeScript directory. */
    public const string PROTOCOL = 'protocol';

    /**
     * The TypeScript type and the validator's rule for each core field type of the blueprint schema
     * v1. The generator-coverage test holds the keys to the field types of the installed
     * blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array FIELD_TYPES = [
        'boolean' => 'boolean, a JSON boolean',
        'date' => 'string, YYYY-MM-DD',
        'datetime' => 'string, RFC 3339 with an offset',
        'decimal' => 'string, a decimal number with at most the field\'s precision and scale',
        'group' => 'an interface of its fields, or a readonly list of them when it repeats',
        'integer' => 'number, an integer a JavaScript number holds exactly',
        'long_text' => 'string',
        'rich_text' => 'PortableText, a list of Portable Text blocks',
        'select' => 'a union of its values, or a readonly list of them with multiple',
        'text' => 'string, in its format',
    ];

    /**
     * What the modules hold for a blueprint file of each kind. The generator-coverage test holds the
     * keys to the kinds of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array KINDS = [
        'extension' => 'its fields in the record of the type it extends, under ext.<namespace>',
        'type' => 'a module per record contract version with the record\'s types and its validator',
    ];

    /**
     * @param  Closure(): string  $runtime  gives the source of the runtime module
     * @param  Closure(): list<CodecContract>  $protocol  gives the contracts of the kernel's JSON Schemas
     */
    public function __construct(
        private Closure $runtime,
        private Closure $protocol,
    ) {}

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->typeScriptDirectory;
    }

    /**
     * @throws GenerationFailed
     */
    #[Override]
    public function generate(CompiledSchema $schema, GenerationTarget $target): array
    {
        $directory = $target->typeScriptDirectory;
        $files = [new GeneratedFile($directory.'/'.self::RUNTIME, ($this->runtime)())];

        foreach ($schema->types as $type) {
            $contract = RecordContracts::of($type);
            $files[] = TypeScriptEmitter::emit(
                $contract,
                $directory.'/'.self::RECORDS.'/'.$contract->root->className.'.ts',
                '../validation',
                [
                    sprintf('The record of %s in contract version %d (PRD 8.9), as TypeScript: its JSON', $type->name(), $contract->version),
                    sprintf('form, which the kernel\'s codec %s reads and writes, and a validator', $contract->codecClass),
                    'that checks a JSON value against every rule of the record (PRD 11.12).',
                    '',
                    'Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
                    'this file: change the blueprints and run cms:generate.',
                ],
            );
        }

        foreach (($this->protocol)() as $contract) {
            $name = (string) preg_replace('/Codec(V[0-9]+)\z/', '$1', $contract->codecClass);
            $files[] = TypeScriptEmitter::emit(
                $contract,
                $directory.'/'.self::PROTOCOL.'/'.$name.'.ts',
                '../validation',
                [
                    sprintf('A contract of the kernel, %s, as TypeScript (GUARDRAILS 2.2): its JSON form, which the', $name),
                    sprintf('kernel\'s codec %s reads and writes, and a validator that checks a JSON', $contract->codecClass),
                    'value against every rule of its JSON Schema.',
                    '',
                    'Generated by cms:generate from the JSON Schemas of cboxdk/cms. Do not edit this file: it',
                    'is written again on every run of cms:generate.',
                ],
            );
        }

        return $files;
    }
}
