<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Generation\Domain\Generators;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\CompiledSchema;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\FieldDescriptor;
use Cbox\Cms\Generators\Descriptor\Domain\Dto\TypeDescriptor;
use Cbox\Cms\Generators\Generation\Domain\Dto\GeneratedFile;
use Cbox\Cms\Generators\Generation\Domain\Dto\GenerationTarget;
use Cbox\Cms\Generators\Generation\Domain\GenerationFailed;
use Cbox\Cms\Generators\Generation\Domain\Generator;
use Override;

/**
 * The M0 TypeScript link of the type chain, in `index.ts`: the union type `TypeHandle` of the
 * types, each named `<owner>:<handle>` (TypeDescriptor::name()) because a handle is unique only for
 * its owner, and the interface `TypeFields` that maps each type by that name to its fields and
 * their field types. The owner's fields are keyed by handle, sorted, and the extension fields
 * follow under the reserved key `ext`, by namespace and then by handle, so TypeScript addresses
 * one as `ext.<namespace>.<handle>` (PRD 11.12); the column name `ext__<namespace>__<handle>`
 * belongs to the type table alone. A type without extension fields has no `ext`. Without types,
 * `TypeHandle` is `never` and `TypeFields` the mapped type over it, which has no keys; an empty
 * interface would accept any value that is not null.
 *
 * The output is formatted the way the shared Prettier configuration prints it (printWidth 100,
 * single quotes), so `prettier --check` accepts it unchanged. A union that fits on one line stays
 * on one line; a longer one moves to the next line, and one that does not fit there either gets
 * one member per line with a leading `|`, as Prettier breaks it.
 */
#[Internal]
final readonly class TypeScriptTypeHandles implements Generator
{
    public const string FILE_NAME = 'index.ts';

    /** Prettier's printWidth in js/tooling/prettier.js. */
    public const int PRINT_WIDTH = 100;

    /**
     * The string literal type `TypeFields` gives for each core field type of the blueprint schema
     * v1: its name. A field type without a mapping here is refused as invalid output. The
     * generator-coverage test holds the keys to the field types of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array FIELD_TYPES = [
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'decimal' => 'decimal',
        'group' => 'group',
        'integer' => 'integer',
        'long_text' => 'long_text',
        'rich_text' => 'rich_text',
        'select' => 'select',
        'text' => 'text',
    ];

    /**
     * What the file holds for a blueprint file of each kind. The generator-coverage test holds the
     * keys to the kinds of the installed blueprint.v1.json.
     *
     * @var array<string, string>
     */
    public const array KINDS = [
        'extension' => 'its fields in the TypeFields entry of the type it extends, under ext.<namespace>.<handle>',
        'type' => 'a member <owner>:<handle> of TypeHandle, and an entry of TypeFields under that name with the type\'s own fields',
    ];

    #[Override]
    public function directory(GenerationTarget $target): string
    {
        return $target->typeScriptDirectory;
    }

    #[Override]
    public function generate(CompiledSchema $schema, GenerationTarget $target): array
    {
        $lines = [
            '// The types of the schema roots, named <owner>:<handle>, with the fields of each type.',
            '//',
            '// Generated by cms:generate from the blueprint v1 files below the schema roots. Do not edit',
            '// this file: change the blueprints and run cms:generate.',
            '//',
            '// Schema roots, by owner:',
            ...GeneratedLines::schemaRoots($target, '//   '),
            '',
            '/** Each type in the schema, as <owner>:<handle>. */',
            ...$this->union($schema),
            '',
            '/** The fields of each type: field handle to field type, extension fields under ext.<namespace>. */',
            ...($schema->types === [] ? ['export type TypeFields = { [Handle in TypeHandle]: never };'] : [
                'export interface TypeFields {',
                ...array_merge(...array_map($this->fields(...), $schema->types)),
                '}',
            ]),
        ];

        return [new GeneratedFile(
            $target->typeScriptDirectory.'/'.self::FILE_NAME,
            implode("\n", $lines)."\n",
        )];
    }

    /**
     * @return list<string>
     */
    private function union(CompiledSchema $schema): array
    {
        $members = array_map(static fn (TypeDescriptor $type): string => "'".$type->name()."'", $schema->types);
        $declaration = 'export type TypeHandle =';
        $line = $declaration.' '.($members === [] ? 'never' : implode(' | ', $members)).';';

        if (strlen($line) <= self::PRINT_WIDTH) {
            return [$line];
        }

        $lines = [$declaration];

        if (2 + strlen(implode(' | ', $members)) + 1 <= self::PRINT_WIDTH) {
            return [$declaration, '  '.implode(' | ', $members).';'];
        }

        foreach ($members as $member) {
            $lines[] = '  | '.$member;
        }

        $lines[] = array_pop($lines).';';

        return $lines;
    }

    /**
     * @return list<string>
     *
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fields(TypeDescriptor $type): array
    {
        $lines = ["  '".$type->name()."': {"];

        foreach ($type->ownFields() as $field) {
            $lines[] = sprintf("    %s: '%s';", $field->handle->value, $this->fieldType($field));
        }

        $extensions = $type->extensionFields();

        if ($extensions !== []) {
            $lines[] = '    ext: {';

            foreach ($extensions as $namespace => $fields) {
                $lines[] = '      '.$namespace.': {';

                foreach ($fields as $field) {
                    $lines[] = sprintf("        %s: '%s';", $field->handle->value, $this->fieldType($field));
                }

                $lines[] = '      };';
            }

            $lines[] = '    };';
        }

        $lines[] = '  };';

        return $lines;
    }

    /**
     * @throws GenerationFailed with GenerateErrorCode::InvalidOutput
     */
    private function fieldType(FieldDescriptor $field): string
    {
        return GeneratedLines::fieldType(self::class, self::FIELD_TYPES, $field);
    }
}
