<?php

declare(strict_types=1);

namespace Cbox\Cms\Contracts\Codecs;

use Cbox\Cms\Contracts\Attributes\Experimental;
use Cbox\Cms\Contracts\Identity\ClassificationAccess;

/**
 * The JSON codec of one contract version (GUARDRAILS 2.2): the one place the JSON form of a DTO is
 * fixed, generated by cms:generate and never reflecting on anything at run time. A surface that
 * serves a DTO, such as the REST and MCP projections, encodes it with the codec of the contract
 * version it serves, and reads a document with the same codec.
 *
 * encode() writes the canonical JSON of the DTO as a caller with $access may see it: keys sorted,
 * no whitespace, and no field classified above the access (PRD 12.2) or that the DTO holds as
 * Omitted. decode() reads a document back, checks every rule of every value, and refuses a key
 * twice, an unknown key, and a field classified above the access; it throws the core's
 * DecodingFailed with json_malformed or json_invalid.
 *
 * @template TDto of object
 */
#[Experimental]
interface JsonCodec
{
    /**
     * @param  TDto  $dto
     */
    public function encode(object $dto, ClassificationAccess $access): string;

    /**
     * @return TDto
     */
    public function decode(string $json, ClassificationAccess $access): object;
}
