<?php

declare(strict_types=1);

namespace Cbox\Cms\Http\Tests\Rest;

use Cbox\Cms\Contracts\Consistency\RetentionClass;
use Cbox\Cms\Contracts\Consistency\WaitLevel;
use Cbox\Cms\Contracts\Identity\ClassificationAccess;
use Cbox\Cms\Contracts\Receipts\Receipt;
use Cbox\Cms\Core\Codecs\Boundary\Generated\ReceiptCodecV1;
use Cbox\Cms\Core\Registry\Adapter\FileOpenApiDocuments;
use Cbox\Cms\Core\Tests\Pipeline\ExposedWorld;
use Cbox\Cms\Core\Tests\Registry\RegistryFixtures;
use Cbox\Cms\Http\Tests\Rest\Support\RestWorld;
use Opis\JsonSchema\CompliantValidator;
use Opis\JsonSchema\Errors\ErrorFormatter;
use Opis\JsonSchema\Errors\ValidationError;
use PHPUnit\Framework\Assert;
use stdClass;

/*
 * The OpenAPI document cms:build writes next to the registry (GUARDRAILS 2.1: routes and OpenAPI
 * are generated by cms:build from the registry; PRD 8.8). The action of cms:build compiles the REST
 * fixtures and writes bootstrap/cache/cms/openapi.json into a scratch directory; the test validates
 * it against the JSON Schema of OpenAPI 3.1 that the OpenAPI Initiative publishes (shipped by
 * devizzent/cebe-php-openapi), and reads the test-only action's route and schemas from it.
 *
 * opis/json-schema 2.6 resolves a `$dynamicRef` to the root of the document instead of to its
 * `$dynamicAnchor`, so every schema object would be checked as a whole OpenAPI document. The
 * OpenAPI schema has one dynamic anchor, `meta` at #/$defs/schema, and nothing extends its dynamic
 * scope, so `"$dynamicRef": "#meta"` there means `"$ref": "#/$defs/schema"`; openApiSchema() makes
 * that replacement after checking that the anchor is the only one and sits there. The validator is
 * opis's CompliantValidator, which never writes the schema's defaults into the document.
 */

const OPENAPI_31_SCHEMA = __DIR__.'/../../../../vendor/devizzent/cebe-php-openapi/schemas/openapi-v3.1.json';

afterEach(function (): void {
    RegistryFixtures::cleanUp();
});

/**
 * The OpenAPI 3.1 schema, with its dynamic references to its one dynamic anchor written as the
 * plain references they resolve to.
 */
function openApiSchema(): string
{
    $schema = file_get_contents(OPENAPI_31_SCHEMA);
    Assert::assertIsString($schema);
    $decoded = json_decode($schema, false, 512, JSON_THROW_ON_ERROR);
    Assert::assertInstanceOf(stdClass::class, $decoded);

    expect(substr_count($schema, '"$dynamicAnchor"'))->toBe(1)
        ->and(openApiAt($decoded, '$defs', 'schema', '$dynamicAnchor'))->toBe('meta')
        ->and(preg_match_all('/"\$dynamicRef": "([^"]*)"/', $schema, $references))->toBeGreaterThan(0)
        ->and(array_unique($references[1]))->toBe(['#meta']);

    return str_replace('"$dynamicRef": "#meta"', '"$ref": "#/$defs/schema"', $schema);
}

/**
 * The document cms:build wrote, decoded with objects as stdClass.
 */
function openApiDocument(): stdClass
{
    $directory = RegistryFixtures::scratch();
    RestWorld::build($directory);
    $json = file_get_contents($directory.'/'.FileOpenApiDocuments::FILE);
    Assert::assertIsString($json);
    $document = json_decode($json, false, 512, JSON_THROW_ON_ERROR);
    Assert::assertInstanceOf(stdClass::class, $document);

    return $document;
}

/**
 * The validation errors of a value against a schema, by JSON pointer; empty when it is valid.
 *
 * @return array<string, list<string>>
 */
function openApiErrors(mixed $value, string $schema): array
{
    $validator = new CompliantValidator;
    $validator->setMaxErrors(20);
    $error = $validator->validate($value, $schema)->error();

    if (! $error instanceof ValidationError) {
        return [];
    }

    /** @var array<string, list<string>> $errors */
    $errors = new ErrorFormatter()->format($error, true);

    return $errors;
}

/**
 * A value below the document, by keys.
 */
function openApiAt(stdClass $document, string ...$keys): mixed
{
    $value = $document;

    foreach ($keys as $key) {
        Assert::assertInstanceOf(stdClass::class, $value, sprintf('No object holds %s.', implode(' > ', $keys)));
        Assert::assertTrue(property_exists($value, $key), sprintf('The document has no %s.', implode(' > ', $keys)));
        $value = $value->{$key};
    }

    return $value;
}

/**
 * The keys of an object below the document, as strings.
 *
 * @return list<string>
 */
function openApiKeys(stdClass $document, string ...$keys): array
{
    $object = openApiAt($document, ...$keys);
    Assert::assertInstanceOf(stdClass::class, $object);

    return array_map(strval(...), array_keys(get_object_vars($object)));
}

it('writes an OpenAPI 3.1 document that the OpenAPI 3.1 schema accepts', function (): void {
    $document = openApiDocument();

    expect(openApiErrors($document, openApiSchema()))->toBe([])
        ->and(openApiAt($document, 'openapi'))->toBe('3.1.1')
        ->and(openApiAt($document, 'info', 'version'))->toBe('v1');
});

it('lists the test-only action\'s compiled route with its command\'s schema, the envelope\'s headers and the receipt and problem responses', function (): void {
    $document = openApiDocument();
    $parameters = openApiAt($document, 'paths', '/v1/commands/probe.rename/v1', 'post', 'parameters');
    Assert::assertIsArray($parameters);

    expect(openApiKeys($document, 'paths'))->toBe(['/v1/commands/probe.rename/v1', '/v1/queries/probe.cards/v1'])
        ->and(openApiAt($document, 'paths', '/v1/commands/probe.rename/v1', 'post', 'operationId'))->toBe('command.probe.rename.v1')
        ->and(openApiAt($document, 'paths', '/v1/commands/probe.rename/v1', 'post', 'requestBody', 'content', 'application/json', 'schema', '$ref'))->toBe('#/components/schemas/command.probe.rename.v1')
        ->and(array_map(static fn (mixed $parameter): mixed => $parameter instanceof stdClass ? $parameter->{'$ref'} : null, $parameters))->toBe([
            '#/components/parameters/CorrelationId',
            '#/components/parameters/DryRun',
            '#/components/parameters/IdempotencyKey',
            '#/components/parameters/WaitLevel',
        ])
        ->and(openApiAt($document, 'components', 'parameters', 'IdempotencyKey', 'name'))->toBe('Idempotency-Key')
        ->and(openApiAt($document, 'components', 'parameters', 'IdempotencyKey', 'required'))->toBeTrue()
        ->and(openApiKeys($document, 'paths', '/v1/commands/probe.rename/v1', 'post', 'responses'))->toBe(['200', '202', '4XX', '5XX'])
        ->and(openApiAt($document, 'paths', '/v1/commands/probe.rename/v1', 'post', 'responses', '202', 'content', 'application/json', 'schema', '$ref'))->toBe('#/components/schemas/Receipt')
        ->and(openApiAt($document, 'components', 'responses', 'Rejected', 'content', 'application/problem+json', 'schema', '$ref'))->toBe('#/components/schemas/Problem')
        ->and(openApiAt($document, 'components', 'schemas', 'command.probe.rename.v1', '$id'))->toBe('urn:cbox-cms:command:probe.rename.v1')
        ->and(openApiAt($document, 'components', 'schemas', 'command.probe.rename.v1', 'title'))->toBe('probe.rename, version 1');
});

it('lists the test-only query\'s route with its query parameter and its result', function (): void {
    $document = openApiDocument();

    expect(openApiAt($document, 'paths', '/v1/queries/probe.cards/v1', 'get', 'operationId'))->toBe('query.probe.cards.v1')
        ->and(openApiAt($document, 'paths', '/v1/queries/probe.cards/v1', 'get', 'responses', '200', 'content', 'application/json', 'schema', '$ref'))->toBe('#/components/schemas/result.probe.cards.v1')
        ->and(openApiAt($document, 'components', 'schemas', 'query.probe.cards.v1', '$id'))->toBe('urn:cbox-cms:query:probe.cards.v1')
        ->and(openApiAt($document, 'components', 'schemas', 'result.probe.cards.v1', '$id'))->toBe('urn:cbox-cms:result:probe.cards.v1');
});

it('gives each schema an $id of its own, so its references to its own definitions resolve inside it', function (): void {
    $document = openApiDocument();
    $receipt = json_encode(openApiAt($document, 'components', 'schemas', 'Receipt'), JSON_THROW_ON_ERROR);
    $command = json_encode(openApiAt($document, 'components', 'schemas', 'command.probe.rename.v1'), JSON_THROW_ON_ERROR);
    $world = new ExposedWorld;

    expect(openApiErrors(json_decode(new ReceiptCodecV1()->encode(Receipt::dryRun(WaitLevel::Commit, RetentionClass::Standard), ClassificationAccess::Public), false, 512, JSON_THROW_ON_ERROR), $receipt))->toBe([])
        ->and(openApiErrors(json_decode($world->document(), false, 512, JSON_THROW_ON_ERROR), $command))->toBe([])
        ->and(openApiErrors(json_decode('{"entry":"x","fields":{},"home":"x","type":"x"}', false, 512, JSON_THROW_ON_ERROR), $command))->not->toBe([])
        ->and(openApiAt($document, 'components', 'schemas', 'Receipt', '$id'))->toBe('urn:cbox-cms:receipt:v1')
        ->and(openApiAt($document, 'components', 'schemas', 'Problem', '$id'))->toBe('urn:cbox-cms:problem:v1');
});

it('writes the same bytes for the same registry and codecs', function (): void {
    $first = RegistryFixtures::scratch();
    $second = RegistryFixtures::scratch();
    RestWorld::build($first);
    RestWorld::build($second);

    expect(file_get_contents($first.'/'.FileOpenApiDocuments::FILE))->toBe(file_get_contents($second.'/'.FileOpenApiDocuments::FILE));
});
