// What @cboxdk/cms-panel/ui re-exports of the component kit: its @stable exports
// (decision D1 of the panel extension architecture).
//
// Generated by npm run generate:sdk from the stability tags of js/ui-kit/src/index.ts. Do not edit
// this file: change the kit's tags and run npm run generate:sdk.

export { DEFAULT_KIT_LOCALE, KIT_LOCALES, KitI18nProvider, isKitLocale } from '@cboxdk/cms-ui-kit';
export type {
  KitI18nProviderProps,
  KitLocale,
  ThemeTokenName,
  TokenName,
} from '@cboxdk/cms-ui-kit';
