<?php

declare(strict_types=1);

namespace Cbox\Cms\Core\Registry\Domain;

use Cbox\Cms\Contracts\Attributes\Internal;
use Cbox\Cms\Core\Registry\Domain\Dto\CompiledRegistry;
use Cbox\Cms\Core\Registry\Domain\Dto\OpenApiDocument;

/**
 * The OpenAPI 3.1 document of the REST surface (GUARDRAILS 2.1: routes and OpenAPI are generated by
 * cms:build from the registry; PRD 8.8), next to the registry cache in bootstrap/cache/cms.
 *
 * describe() documents every route of the registry's rest.php with the JSON Schemas of the codecs
 * that read and write it, and the kernel's receipt and problem details; write() puts it in place
 * as a whole. cms:build describes before it writes the registry, so a registry whose REST surface
 * cannot be described is never written.
 */
#[Internal]
interface OpenApiDocuments
{
    /**
     * @throws RegistryBuildFailed with registry_surface_without_codec, naming every route whose
     *                             command or query has no codec
     */
    public function describe(CompiledRegistry $registry): OpenApiDocument;

    /**
     * Replaces the document as a whole, so a reader never sees half of it.
     *
     * @throws RegistryCacheUnwritable
     */
    public function write(OpenApiDocument $document): void;
}
