<?php

declare(strict_types=1);

namespace Cbox\Cms\Generators\Tests\Protocol\Fixtures;

use Cbox\Cms\Contracts\Attributes\Experimental;
use Cbox\Cms\Contracts\Codecs\JsonCodec;
use Cbox\Cms\Contracts\Consistency\ProjectionName;
use Cbox\Cms\Contracts\Identity\ClassificationAccess;
use Cbox\Cms\Contracts\Ids\ChangesetId;
use Cbox\Cms\Contracts\Results\FieldPath;
use Cbox\Cms\Core\Codecs\Boundary\JsonText;
use Cbox\Cms\Core\Codecs\Boundary\JsonValues;
use Cbox\Cms\Core\Codecs\Domain\DecodingFailed;
use Cbox\Cms\Core\Codecs\Domain\EncodingFailed;
use Cbox\Cms\Generators\Tests\Codec\Fixtures\Step;
use Cbox\Cms\Generators\Tests\Codec\Fixtures\Tone;
use DateTimeImmutable;
use Override;
use stdClass;

/**
 * The JSON codec of Parcel, contract version 1 (GUARDRAILS 2.2): Parcel as parcel.v1.json.
 *
 * Generated by composer generate:protocol from parcel.v1.json in the contracts module.
 * Do not edit this file: change the schema and run composer generate:protocol.
 *
 * @implements JsonCodec<Parcel>
 */
#[Experimental]
final readonly class ParcelCodecV1 implements JsonCodec
{
    /** The contract version this codec reads and writes. */
    public const int VERSION = 1;

    /**
     * The canonical JSON of $dto as a caller with $access may see it: sorted keys, no
     * whitespace, and without every field classified above the access (PRD 12.2) or held as
     * Omitted.
     *
     * @param  Parcel  $dto
     *
     * @throws EncodingFailed when the DTO holds a value that has no form in the contract
     */
    #[Override]
    public function encode(object $dto, ClassificationAccess $access): string
    {
        return JsonText::encode($this->encodeParcel($dto));
    }

    /**
     * The DTO a JSON document holds, read as a caller with $access: a field classified above
     * the access must be absent, and is Omitted, as is an optional field that is absent.
     *
     * @throws DecodingFailed with json_malformed or json_invalid
     */
    #[Override]
    public function decode(string $json, ClassificationAccess $access): Parcel
    {
        return $this->decodeParcel(JsonText::decode($json));
    }

    private function encodeParcel(Parcel $object): stdClass
    {
        $json = new stdClass;
        $json->box = $this->encodeBox($object->box);
        $json->count = $object->count;
        $json->fragile = $object->fragile;
        $json->id = $object->id instanceof ChangesetId ? $object->id->toString() : null;
        $json->label = $object->label;
        $json->note = $object->note;
        $json->owner = $object->owner instanceof Box ? $this->encodeBox($object->owner) : null;
        $json->sent_at = $object->sentAt instanceof DateTimeImmutable ? JsonValues::encodeDatetime($object->sentAt) : null;
        $json->step = $object->step->value;
        $json->tags = array_map(static fn (ProjectionName $item): mixed => $item->value, $object->tags);
        $json->tone = $object->tone->value;

        return $json;
    }

    private function decodeParcel(stdClass $value): Parcel
    {
        $object = JsonValues::object($value, null, ['box', 'count', 'fragile', 'id', 'label', 'note', 'owner', 'sent_at', 'step', 'tags', 'tone']);

        return JsonValues::build(null, fn (): Parcel => new Parcel(
            label: JsonValues::required($object, 'label', null, static fn (mixed $value, FieldPath $at): string => JsonValues::text($value, $at, minLength: 1, maxLength: 20)),
            step: JsonValues::required($object, 'step', null, static fn (mixed $value, FieldPath $at): Step => JsonValues::enum($value, $at, Step::class)),
            id: JsonValues::present($object, 'id', null, static fn (mixed $value, FieldPath $at): ChangesetId => JsonValues::id($value, $at, ChangesetId::fromString(...))),
            sentAt: JsonValues::present($object, 'sent_at', null, static fn (mixed $value, FieldPath $at): DateTimeImmutable => JsonValues::datetime($value, $at)),
            owner: JsonValues::present($object, 'owner', null, $this->decodeBox(...)),
            count: JsonValues::defaulted($object, 'count', null, static fn (mixed $value, FieldPath $at): int => JsonValues::integer($value, $at, min: 0, max: 9), 3),
            tone: JsonValues::defaulted($object, 'tone', null, static fn (mixed $value, FieldPath $at): Tone => JsonValues::enum($value, $at, Tone::class), Tone::Warm),
            fragile: JsonValues::defaulted($object, 'fragile', null, static fn (mixed $value, FieldPath $at): bool => JsonValues::boolean($value, $at), false),
            note: JsonValues::defaultedNullable($object, 'note', null, static fn (mixed $value, FieldPath $at): string => JsonValues::text($value, $at, maxLength: 200), null),
            tags: JsonValues::defaulted($object, 'tags', null, static fn (mixed $value, FieldPath $at): array => JsonValues::list($value, $at, static fn (mixed $item, FieldPath $itemAt): ProjectionName => JsonValues::value($item, $itemAt, static fn (string $text): ProjectionName => new ProjectionName($text)), minItems: 0, maxItems: 4), []),
            box: JsonValues::defaulted($object, 'box', null, $this->decodeBox(...), new Box),
        ));
    }

    private function encodeBox(Box $object): stdClass
    {
        $json = new stdClass;
        $json->size = $object->size;

        return $json;
    }

    private function decodeBox(mixed $value, FieldPath $path): Box
    {
        $object = JsonValues::object($value, $path, ['size']);

        return JsonValues::build($path, static fn (): Box => new Box(
            size: JsonValues::defaulted($object, 'size', $path, static fn (mixed $value, FieldPath $at): int => JsonValues::integer($value, $at, min: 1), 1),
        ));
    }
}
