<?php

declare(strict_types=1);

namespace Cbox\Cms\Tests\Feature\Tooling;

use Cbox\Cms\Tests\Support\Phpstan;
use Cbox\Cms\Tests\Support\Tooling\ComposerScripts;
use Cbox\Cms\Tests\Support\Tooling\ScratchDirectory;
use Cbox\Cms\Tooling\Install\Boundary\ComposerInstallation;
use Cbox\Cms\Tooling\Install\Boundary\InstallCheckOptions;
use Cbox\Cms\Tooling\Install\Domain\ComposerState;
use Cbox\Cms\Tooling\Install\Domain\InstallAudit;
use InvalidArgumentException;
use Symfony\Component\Process\Process;

/*
 * `composer install:check` (tools/bin/install-check.php), the first step of gate 5: vendor/ must
 * be the installation composer.lock and composer.json describe. The regression it guards: M0-T79
 * added the PSR-4 prefix Examples\ to autoload-dev, M0-T80 to M0-T83 added examples that extend
 * classes below it, and the merge queue fast-forwarded the main checkout without
 * `composer install`, so its dumped autoloader had no Examples\ and `composer check` failed the
 * Unit suite at load and 51 Contract tests with "Class not found", while CI, which installs from
 * the lock file, passed. The checkout's generators, then a path package, were also older than
 * composer.lock.
 * The fixture checkouts below are written in the formats Composer writes.
 */

afterEach(function (): void {
    ScratchDirectory::cleanUp();
});

const INSTALL_PATH_PACKAGE_LOCKED = '0.1.x-dev@95606ba2bc82899f89eee721aedf354245ddba1b';

const INSTALL_PATH_PACKAGE_STALE = '0.1.x-dev@41332215f4384713176ed9524461fce443b86d9f';

/**
 * @param  array<string, string>  $packages
 * @param  array<string, list<string>>  $autoload
 */
function installState(array $packages = ['acme/path-package' => INSTALL_PATH_PACKAGE_LOCKED], array $autoload = ['psr-4 Cbox\\Cms\\Tests\\' => ['tests'], 'psr-4 Examples\\' => ['examples']]): ComposerState
{
    return new ComposerState($packages, $autoload);
}

/**
 * A checkout as Composer leaves it: composer.json with autoload-dev, composer.lock with one path
 * package and one package from a VCS, and vendor/composer with installed.json and a dumped
 * autoloader. $dumpedPsr4 holds the lines of autoload_psr4.php's array, $installedPathPackage the
 * reference installed.json has for the path package.
 *
 * @param  list<string>  $dumpedPsr4
 */
function installCheckout(array $dumpedPsr4, string $installedPathPackage = '95606ba2bc82899f89eee721aedf354245ddba1b'): string
{
    $root = ScratchDirectory::make();
    $pathPackage = static fn (string $reference): array => [
        'name' => 'acme/path-package',
        'version' => '0.1.x-dev',
        'dist' => ['type' => 'path', 'url' => 'packages/path-package', 'reference' => $reference],
    ];
    $yaml = [
        'name' => 'symfony/yaml',
        'version' => 'v8.1.6',
        'source' => ['type' => 'git', 'url' => 'https://github.com/symfony/yaml.git', 'reference' => 'a1b2c3'],
        'dist' => ['type' => 'zip', 'url' => 'https://api.github.com/repos/symfony/yaml/zipball/a1b2c3', 'reference' => 'a1b2c3', 'shasum' => ''],
    ];

    ScratchDirectory::write($root.'/composer.json', (string) json_encode([
        'name' => 'acme/checkout',
        'autoload-dev' => [
            'psr-4' => ['Cbox\\Cms\\Tests\\' => 'tests/', 'Examples\\' => 'examples/'],
            'classmap' => ['packages/testkit/tests/Phpstan/Fixtures/'],
        ],
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    ScratchDirectory::write($root.'/composer.lock', (string) json_encode([
        'content-hash' => 'd41d8cd98f00b204e9800998ecf8427e',
        'packages' => [$pathPackage('95606ba2bc82899f89eee721aedf354245ddba1b')],
        'packages-dev' => [$yaml],
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    ScratchDirectory::write($root.'/vendor/composer/installed.json', (string) json_encode([
        'packages' => [
            [...$pathPackage($installedPathPackage), 'install-path' => '../acme/path-package'],
            [...$yaml, 'install-path' => '../symfony/yaml'],
        ],
        'dev' => true,
        'dev-package-names' => ['symfony/yaml'],
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    ScratchDirectory::write($root.'/vendor/composer/autoload_psr4.php', implode("\n", [
        '<?php',
        '',
        '// autoload_psr4.php @generated by Composer',
        '',
        '$vendorDir = dirname(__DIR__);',
        '$baseDir = dirname($vendorDir);',
        '',
        'return array(',
        '    \'Symfony\\\\Component\\\\Yaml\\\\\' => array($vendorDir . \'/symfony/yaml\'),',
        '    \'Acme\\\\PathPackage\\\\\' => array($vendorDir . \'/acme/path-package/src\'),',
        ...$dumpedPsr4,
        ');',
        '',
    ]));
    ScratchDirectory::write($root.'/vendor/composer/autoload_namespaces.php', "<?php\n\n\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn array(\n);\n");

    return $root;
}

function installCheck(string $root): Process
{
    $process = new Process([PHP_BINARY, 'tools/bin/install-check.php', '--root='.$root], Phpstan::root());
    $process->run();

    return $process;
}

const INSTALL_DUMPED_TESTS = '    \'Cbox\\\\Cms\\\\Tests\\\\\' => array($baseDir . \'/tests\'),';

const INSTALL_DUMPED_EXAMPLES = '    \'Examples\\\\\' => array($baseDir . \'/examples\'),';

it('finds no difference when the installation is the one composer.lock and composer.json describe', function (): void {
    expect(InstallAudit::problems(installState(), installState()))->toBe([]);
});

it('reports a PSR-4 prefix composer.json declares that the dumped autoloader lacks, as main had Examples\ after the merge queue', function (): void {
    $dumped = installState(autoload: ['psr-4 Cbox\\Cms\\Tests\\' => ['tests']]);

    expect(InstallAudit::problems(installState(), $dumped))->toBe([
        'composer.json autoloads psr-4 Examples\\ from examples, but the dumped autoloader in vendor/composer does not.',
    ]);
});

it('reports a package installed at another reference than composer.lock, one not installed and one composer.lock does not list', function (): void {
    $locked = installState(['acme/path-package' => INSTALL_PATH_PACKAGE_LOCKED, 'symfony/yaml' => 'v8.1.6@a1b2c3']);
    $installed = installState(['acme/path-package' => INSTALL_PATH_PACKAGE_STALE, 'opis/json-schema' => '2.6.0@d4e5f6']);

    expect(InstallAudit::problems($locked, $installed))->toBe([
        'acme/path-package is installed at '.INSTALL_PATH_PACKAGE_STALE.', but composer.lock has '.INSTALL_PATH_PACKAGE_LOCKED.'.',
        'symfony/yaml v8.1.6@a1b2c3 is in composer.lock, but not installed in vendor/.',
        'opis/json-schema 2.6.0@d4e5f6 is installed in vendor/, but composer.lock does not list it.',
    ]);
});

it('reports a rule whose paths changed and a rule composer.json no longer declares', function (): void {
    $declared = installState(autoload: ['files' => ['helpers.php'], 'psr-4 Examples\\' => ['examples', 'more-examples']]);
    $dumped = installState(autoload: ['psr-0 Legacy_' => ['legacy'], 'psr-4 Examples\\' => ['examples']]);

    expect(InstallAudit::problems($declared, $dumped))->toBe([
        'composer.json autoloads files from helpers.php, but the dumped autoloader in vendor/composer does not.',
        'The dumped autoloader in vendor/composer autoloads psr-0 Legacy_ from legacy, but composer.json no longer does.',
        'composer.json autoloads psr-4 Examples\\ from examples, more-examples, but the dumped autoloader in vendor/composer from examples.',
    ]);
});

it('reads both sides of a checkout from the files Composer writes, with only the root package\'s rules and without trailing slashes', function (): void {
    $installation = ComposerInstallation::at(installCheckout([INSTALL_DUMPED_TESTS, INSTALL_DUMPED_EXAMPLES]));

    expect($installation->declared())->toEqual(new ComposerState(
        ['acme/path-package' => INSTALL_PATH_PACKAGE_LOCKED, 'symfony/yaml' => 'v8.1.6@a1b2c3'],
        ['psr-4 Cbox\\Cms\\Tests\\' => ['tests'], 'psr-4 Examples\\' => ['examples']],
    ))
        ->and($installation->installed())->toEqual($installation->declared());
});

it('passes a checkout whose vendor/ is current', function (): void {
    $process = installCheck(installCheckout([INSTALL_DUMPED_TESTS, INSTALL_DUMPED_EXAMPLES]));

    expect($process->getExitCode())->toBe(0, $process->getErrorOutput())
        ->and($process->getOutput())->toBe("install:check: vendor/ is the installation composer.lock and composer.json describe.\n");
});

it('fails the checkout main was after the merge queue: no Examples\ in the dumped autoloader and a path package older than composer.lock', function (): void {
    $process = installCheck(installCheckout([INSTALL_DUMPED_TESTS], '41332215f4384713176ed9524461fce443b86d9f'));

    expect($process->getExitCode())->toBe(1)
        ->and($process->getOutput())->toBe(implode("\n", [
            'acme/path-package is installed at '.INSTALL_PATH_PACKAGE_STALE.', but composer.lock has '.INSTALL_PATH_PACKAGE_LOCKED.'.',
            'composer.json autoloads psr-4 Examples\\ from examples, but the dumped autoloader in vendor/composer does not.',
            '',
        ]))
        ->and($process->getErrorOutput())->toContain('(2 differences)', InstallAudit::FIX);
});

it('fails a checkout without an installation, and refuses unknown arguments with exit 2', function (): void {
    $root = installCheckout([INSTALL_DUMPED_TESTS, INSTALL_DUMPED_EXAMPLES]);
    unlink($root.'/vendor/composer/installed.json');
    $missing = installCheck($root);
    $usage = new Process([PHP_BINARY, 'tools/bin/install-check.php', '--fast'], Phpstan::root());
    $usage->run();

    expect($missing->getExitCode())->toBe(1)
        ->and($missing->getErrorOutput())->toBe("Cannot read vendor/composer/installed.json.\n".InstallAudit::FIX."\n")
        ->and($usage->getExitCode())->toBe(2)
        ->and($usage->getErrorOutput())->toBe("Unknown or repeated argument [--fast].\n".InstallCheckOptions::USAGE."\n")
        ->and(static fn (): InstallCheckOptions => InstallCheckOptions::parse(['--root=a', '--root=b']))->toThrow(InvalidArgumentException::class);
});

it('is the Composer script install:check, with a description', function (): void {
    expect(ComposerScripts::steps('install:check'))->toBe(['@php tools/bin/install-check.php'])
        ->and(ComposerScripts::description('install:check'))->toContain('gate 5', 'composer install');
});

it('has the merge queue\'s regression gate install the main checkout before it runs the gates', function (): void {
    $workflow = (string) file_get_contents(Phpstan::root().'/.claude/workflows/cms-milestone.js');
    $start = strpos($workflow, 'Block-wide regression gate for ${BLOCK} on main in ${REPO}');

    expect($start)->toBeInt();

    $prompt = substr($workflow, (int) $start, (int) strpos($workflow, '`,', (int) $start) - (int) $start);
    $install = strpos($prompt, '"composer install" and "npm ci" in ${REPO}');
    $check = strpos($prompt, '"composer check"');

    expect($install)->toBeInt()
        ->and($check)->toBeInt()
        ->and($install < $check)->toBeTrue();
});
